
export const attributes = [
  {id: 1, ord: 1, nam: "cetli", abr: "c, sn", rep: "*", typ: "text"},
  {id: 2, ord: 2, nam: "példány", abr: "p, e", rep: "*pd", typ: "tel"},
  {id: 3, ord: 3, nam: "hím", abr: "h", rep: "*h", typ: "tel"},
  {id: 4, ord: 4, nam: "nőstény", abr: "n", rep: "*n", typ: "tel"},
  {id: 5, ord: 5, nam: "adult", abr: "ad", rep: "*ad", typ: "tel"},
  {id: 6, ord: 6, nam: "juvenilis", abr: "j", rep: "*juv", typ: "tel"},
  {id: 7, ord: 7, nam: "subadult", abr: "sub", rep: "*sub", typ: "tel"},
  {id: 8, ord: 8, nam: "immature", abr: "imm", rep: "*imm", typ: "tel"},
  {id: 9, ord: 9, nam: "pullus", abr: "pul", rep: "*pull", typ: "tel"},
  {id: 10, ord: 10, nam: "tojás", abr: "toj", rep: "* tojás", typ: "tel"},
  {id: 11, ord: 11, nam: "ének", abr: "en", rep: null, typ: null},
  {id: 12, ord: 12, nam: "hang", abr: "hg", rep: null, typ: null},
  {id: 13, ord: 13, nam: "riaszt", abr: "ri", rep: null, typ: null},
  {id: 14, ord: 14, nam: "látva is", abr: "ls", rep: null, typ: null},
  {id: 15, ord: 15, nam: "átrepülő", abr: "at", rep: null, typ: null},
  {id: 16, ord: 16, nam: "dög", abr: "dg", rep: null, typ: null},
  {id: 17, ord: 17, nam: "virágzik", abr: "vir, flos", rep: null, typ: null},
  {id: 18, ord: 18, nam: "közös csapatban", abr: "kcs", rep: null, typ: null},
  {id: 19, ord: 19, nam: "több csapatban", abr: "tcs", rep: null, typ: null},
  {id: 20, ord: 20, nam: "irány", abr: "ir", rep: "*-felé", typ: "lis", dat: "É, ÉK, K, DK, D, DNy, Ny, ÉNy"},
  {id: 21, ord: 21, nam: "néhány pd", abr: "npd", rep: null, typ: null},
  {id: 22, ord: 22, nam: "több pd", abr: "tpd", rep: null, typ: null},
  {id: 23, ord: 23, nam: "viselkedés", abr: "vs", rep: "*", typ: "lis", dat: "fészkelő, vonuló, telelő, kóborló"},
  {id: 24, ord: 24, nam: "gyakoriság", abr: "gy", rep: "*", typ: "lis", dat: "igen ritka, ritka, szórványos, gyakori, tömeges"},
  {id: 25, ord: 25, nam: "előfordulás", abr: "el", rep: "*", typ: "lis", dat: "előfordul, többfelé előfordul, mindenfelé előfordul"},
  {id: 26, ord: 26, nam: "fészek", abr: "fsz", rep: null, typ: null},
  {id: 27, ord: 27, nam: "nyom", abr: "nym", rep: null, typ: null},
  {id: 28, ord: 28, nam: "folt", abr: "flt", rep: null, typ: null},
  {id: 29, ord: 29, nam: "odú", abr: "od", rep: null, typ: null},
  {id: 30, ord: 30, nam: "herbárium doboz", abr: "hdb", rep: "doboz: *", typ: "tel"},
  {id: 31, ord: 31, nam: "herbárium szám", abr: "hno", rep: "no: *", typ: "tel"},
  {id: 32, ord: 32, nam: "A-D érték", abr: "ab", rep: "A-D: *", typ: "lis", dat: "+, +-1, 1, 1-2, 2, 2-3, 3, 3-4, 4, 4-5, 5"},
  {id: 33, ord: 33, nam: "birding.hu", abr: "bir", rep: "birding.hu/*", typ: "tel"},
  {id: 34, ord: 34, nam: "izeltlabuak.hu", abr: "ize", rep: "izeltlabuak.hu/*", typ: "tel"},
  {id: 35, ord: 35, nam: "fotó", abr: "ft", rep: null, typ: null},
  {id: 36, ord: 36, nam: "fotóról határozva", abr: "fh", rep: null, typ: null},
  {id: 37, ord: 37, nam: "kétes", abr: "ket", rep: null, typ: null},
  {id: 38, ord: 38, nam: "ellenőrizendő", abr: "ell", rep: null, typ: null},
  {id: 39, ord: 39, nam: "dátum", abr: "dt", rep: "d: *", typ: "date"},
  {id: 40, ord: 40, nam: "időpont", abr: "idp", rep: "*-kor", typ: "time"},
  {id: 41, ord: 41, nam: "kezdés", abr: "kez", rep: "*-", typ: "time"},
  {id: 42, ord: 42, nam: "befejezés", abr: "bef", rep: "-*", typ: "time"},
  {id: 43, ord: 43, nam: "note", abr: "nt", rep: "*", typ: "note"},
  {id: 44, ord: 44, nam: "rögzítve", abr: "rg", rep: "*", typ: "time"},
]

export const observers = [
  {id: 1, nam: "Molnár Márton"}, 
  {id: 2, nam: "Tőgye János"}, 
  {id: 3, nam: "Bodor István"}, 
  {id: 4, nam: "Balázsi Péter"}, 
  {id: 5, nam: "Somogyi Csaba"}, 
  {id: 6, nam: "Mohi Edina"},
  {id: 7, nam: "Ampovics Zsolt"},
  {id: 8, nam: "Mónus Gábor"}, 
  {id: 9, nam: "Egyed Pál"}, 
  {id: 10, nam: "ifj. Vasuta Gábor"}, 
  {id: 11, nam: "Veszelinov Ottó"}, 
  {id: 12, nam: "Őze Péter"}, 
  {id: 13, nam: "Kovács Norbert"}, 
  {id: 14, nam: "Nemes Kristóf"},
  {id: 15, nam: "Rajna Tamás"}, 
  {id: 16, nam: "Berényi Zsombor"},
  {id: 17, nam: "Kurfis Ilona"}, 
  {id: 18, nam: "Szokács Krisztián"}, 
  {id: 19, nam: "Fábiánné Zsuzsa	"}, 
  {id: 20, nam: "Eredics Bálint"},
  {id: 21, nam: "Hany Istók"},
  {id: 22, nam: "Ócsag Attila"},
]