export const birds = [
{id: 1, hun: "Strucc", ltn: "Struthio camelus", abr: "", mon: null},
{id: 2, hun: "Sujtásos fütyülőlúd", ltn: "Dendrocygna bicolor", abr: "sfld", mon: "111111111111"},
{id: 3, hun: "Bengáli fütyülőlúd", ltn: "Dendrocygna javanica", abr: "", mon: null},
{id: 4, hun: "Örvös lúd", ltn: "Branta bernicla", abr: "orld", mon: "111111111111"},
{id: 5, hun: "Vörösnyakú lúd", ltn: "Branta ruficollis", abr: "vnld", mon: "111111111111"},
{id: 6, hun: "Kanadai lúd", ltn: "Branta canadensis", abr: "knld", mon: "111111111111"},
{id: 7, hun: "Apácalúd", ltn: "Branta leucopsis", abr: "apld", mon: "111111111111"},
{id: 8, hun: "Alaszkai lúd", ltn: "Branta hutchinsii", abr: "", mon: null},
{id: 9, hun: "Indiai lúd", ltn: "Anser indicus", abr: "inld", mon: "111111111111"},
{id: 10, hun: "Hólúd", ltn: "Anser rossii", abr: "", mon: null},
{id: 11, hun: "Sarki lúd", ltn: "Anser caerulescens", abr: "skld", mon: "111111111111"},
{id: 12, hun: "Nyári lúd", ltn: "Anser anser", abr: "nyld", mon: "333333333333"},
{id: 13, hun: "Vetési lúd", ltn: "Anser fabalis", abr: "vtld", mon: "111111111111"},
{id: 14, hun: "Rövidcsőrű lúd", ltn: "Anser brachyrhynchus", abr: "rcld", mon: "111111111111"},
{id: 15, hun: "Tundralúd", ltn: "Anser serrirostris", abr: "trld", mon: "222111111222"},
{id: 16, hun: "Vetési lúd faj", ltn: "Anser serrirostris v fabalis", abr: "", mon: "222111111222"},
{id: 17, hun: "Nagy lilik", ltn: "Anser albifrons", abr: "nlil,ngll", mon: "333322223333"},
{id: 18, hun: "Kis lilik", ltn: "Anser erythropus", abr: "klil,ksll", mon: "111111111111"},
{id: 19, hun: "Fekete hattyú", ltn: "Cygnus atratus", abr: "", mon: null},
{id: 20, hun: "Bütykös hattyú", ltn: "Cygnus olor", abr: "bkha,bkht", mon: "333333333333"},
{id: 21, hun: "Kis hattyú", ltn: "Cygnus columbianus", abr: "ksht", mon: "111111111111"},
{id: 22, hun: "Énekes hattyú", ltn: "Cygnus cygnus", abr: "enht", mon: "111111111111"},
{id: 23, hun: "Tüskésszárnyú lúd", ltn: "Plectropterus gambensis", abr: "", mon: null},
{id: 24, hun: "Bütykös fényréce", ltn: "Sarkidiornis melanotos", abr: "", mon: null},
{id: 25, hun: "Nílusi lúd", ltn: "Alopochen aegyptiaca", abr: "nlld", mon: "333333333333"},
{id: 26, hun: "Bütykös ásólúd", ltn: "Tadorna tadorna", abr: "bald", mon: "222222222222"},
{id: 27, hun: "Vörös ásólúd", ltn: "Tadorna ferruginea", abr: "vald", mon: "111111111111"},
{id: 28, hun: "Pézsmaréce", ltn: "Cairina moschata", abr: "", mon: null},
{id: 29, hun: "Kisasszonyréce", ltn: "Aix sponsa", abr: "", mon: null},
{id: 30, hun: "Mandarinréce", ltn: "Aix galericulata", abr: "mdrc", mon: "222222222222"},
{id: 31, hun: "Örvös törpelúd", ltn: "Nettapus coromandelianus", abr: "", mon: null},
{id: 32, hun: "Cifra réce", ltn: "Sibirionetta formosa", abr: "", mon: "000000000000"},
{id: 33, hun: "Böjti réce", ltn: "Spatula querquedula", abr: "btrc", mon: "233333333322"},
{id: 34, hun: "Fahéjszínű réce", ltn: "Spatula cyanoptera", abr: "", mon: null},
{id: 35, hun: "Kékszárnyú réce", ltn: "Spatula discors", abr: "ksrc", mon: "111111111111"},
{id: 36, hun: "Kanalas réce", ltn: "Spatula clypeata", abr: "knrc", mon: "333333333333"},
{id: 37, hun: "Kendermagos réce", ltn: "Mareca strepera", abr: "kdrc", mon: "333333333333"},
{id: 38, hun: "Sarlós réce", ltn: "Mareca falcata", abr: "", mon: null},
{id: 39, hun: "Fütyülő réce", ltn: "Mareca penelope", abr: "ftrc", mon: "333333333333"},
{id: 40, hun: "Álarcos réce", ltn: "Mareca americana", abr: "", mon: "111111111111"},
{id: 41, hun: "Tőkés réce", ltn: "Anas platyrhynchos", abr: "tore,tkrc", mon: "333333333333"},
{id: 42, hun: "Kormos réce", ltn: "Anas rubripes", abr: "", mon: null},
{id: 43, hun: "Bantu réce", ltn: "Anas capensis", abr: "", mon: null},
{id: 44, hun: "Piroscsőrű réce", ltn: "Anas erythrorhyncha", abr: "", mon: null},
{id: 45, hun: "Nyílfarkú réce", ltn: "Anas acuta", abr: "nfrc", mon: "333333333333"},
{id: 46, hun: "Csörgő réce", ltn: "Anas crecca", abr: "csrc", mon: "333332233333"},
{id: 47, hun: "Zöldszárnyú réce", ltn: "Anas carolinensis", abr: "", mon: "111111111111"},
{id: 48, hun: "Márványos réce", ltn: "Marmaronetta angustirostris", abr: "mvrc", mon: "111111111111"},
{id: 49, hun: "Üstökösréce", ltn: "Netta rufina", abr: "usrc", mon: "333333333333"},
{id: 50, hun: "Feketefejű üstökösréce", ltn: "Netta erythrophthalma", abr: "", mon: null},
{id: 51, hun: "Rókafejű réce", ltn: "Aythya valisineria", abr: "", mon: null},
{id: 52, hun: "Amerikai barátréce", ltn: "Aythya americana", abr: "", mon: null},
{id: 53, hun: "Barátréce", ltn: "Aythya ferina", abr: "brrc", mon: "333333333333"},
{id: 54, hun: "Cigányréce", ltn: "Aythya nyroca", abr: "cgrc", mon: "233333333332"},
{id: 55, hun: "Örvös réce", ltn: "Aythya collaris", abr: "orrc", mon: "111111111111"},
{id: 56, hun: "Kontyos réce", ltn: "Aythya fuligula", abr: "ktrc", mon: "333333333333"},
{id: 57, hun: "Hegyi réce", ltn: "Aythya marila", abr: "hgrc", mon: "222211112222"},
{id: 58, hun: "Búbos réce", ltn: "Aythya affinis", abr: "bbrc", mon: "111111111111"},
{id: 59, hun: "Steller-pehelyréce", ltn: "Polysticta stelleri", abr: "sprc", mon: "111111111111"},
{id: 60, hun: "Pápaszemes pehelyréce", ltn: "Somateria fischeri", abr: "", mon: null},
{id: 61, hun: "Cifra pehelyréce", ltn: "Somateria spectabilis", abr: "cprc", mon: "111111111111"},
{id: 62, hun: "Pehelyréce", ltn: "Somateria mollissima", abr: "phrc", mon: "111111111111"},
{id: 63, hun: "Tarka réce", ltn: "Histrionicus histrionicus", abr: "", mon: null},
{id: 64, hun: "Pápaszemes réce", ltn: "Melanitta perspicillata", abr: "", mon: null},
{id: 65, hun: "Füstös réce", ltn: "Melanitta fusca", abr: "fsrc", mon: "111111111111"},
{id: 66, hun: "Tükrös réce", ltn: "Melanitta deglandi", abr: "", mon: null},
{id: 67, hun: "Stejneger-réce", ltn: "Melanitta stejnegeri", abr: "", mon: null},
{id: 68, hun: "Fekete réce", ltn: "Melanitta nigra", abr: "fkrc", mon: "111111111111"},
{id: 69, hun: "Nyerges réce", ltn: "Melanitta americana", abr: "", mon: null},
{id: 70, hun: "Jegesréce", ltn: "Clangula hyemalis", abr: "jgrc", mon: "111111111111"},
{id: 71, hun: "Fehérfejű kerceréce", ltn: "Bucephala albeola", abr: "", mon: null},
{id: 72, hun: "Kerceréce", ltn: "Bucephala clangula", abr: "kcrc", mon: "333322223333"},
{id: 73, hun: "Izlandi kerceréce", ltn: "Bucephala islandica", abr: "", mon: null},
{id: 74, hun: "Kis bukó", ltn: "Mergellus albellus", abr: "ksbu,ksbk", mon: "333311112333"},
{id: 75, hun: "Csuklyás bukó", ltn: "Lophodytes cucullatus", abr: "csbk", mon: "111111111111"},
{id: 76, hun: "Nagy bukó", ltn: "Mergus merganser", abr: "ngbu,ngbk", mon: "333322223333"},
{id: 77, hun: "Örvös bukó", ltn: "Mergus serrator", abr: "orbk,orbu", mon: "222111111222"},
{id: 78, hun: "Halcsontfarkú réce", ltn: "Oxyura jamaicensis", abr: "hfrc", mon: "111111111111"},
{id: 79, hun: "Kékcsőrű réce", ltn: "Oxyura leucocephala", abr: "", mon: "111111111111"},
{id: 80, hun: "Sisakos gyöngytyúk", ltn: "Numida meleagris", abr: "", mon: null},
{id: 81, hun: "Kaliforniai búbosfürj", ltn: "Callipepla californica", abr: "", mon: null},
{id: 82, hun: "Bozótfürj", ltn: "Colinus virginianus", abr: "", mon: null},
{id: 83, hun: "Császármadár", ltn: "Tetrastes bonasia", abr: "csmd", mon: "111111111111"},
{id: 84, hun: "Siketfajd", ltn: "Tetrao urogallus", abr: "skfd", mon: "111111111111"},
{id: 85, hun: "Nyírfajd", ltn: "Lyrurus tetrix", abr: "nyfd", mon: "111111111111"},
{id: 86, hun: "Kaukázusi nyírfajd", ltn: "Lyrurus mlokosiewiczi", abr: "", mon: null},
{id: 87, hun: "Havasi hófajd", ltn: "Lagopus muta", abr: "", mon: null},
{id: 88, hun: "Sarki hófajd", ltn: "Lagopus lagopus", abr: "", mon: null},
{id: 89, hun: "Kaukázusi királyfogoly", ltn: "Tetraogallus caucasicus", abr: "", mon: null},
{id: 90, hun: "Kaszpi királyfogoly", ltn: "Tetraogallus caspius", abr: "", mon: null},
{id: 91, hun: "Szirtifogoly", ltn: "Alectoris graeca", abr: "", mon: null},
{id: 92, hun: "Csukár", ltn: "Alectoris chukar", abr: "", mon: null},
{id: 93, hun: "Barnanyakú szirtifogoly", ltn: "Alectoris barbara", abr: "", mon: null},
{id: 94, hun: "Vörös szirtifogoly", ltn: "Alectoris rufa", abr: "", mon: null},
{id: 95, hun: "Álarcos sivatagifogoly", ltn: "Ammoperdix griseogularis", abr: "", mon: null},
{id: 96, hun: "Fehérfülű sivatagifogoly", ltn: "Ammoperdix heyi", abr: "", mon: null},
{id: 97, hun: "Örvös frankolin", ltn: "Francolinus francolinus", abr: "", mon: null},
{id: 98, hun: "Koronás frankolin", ltn: "Pternistis erckelii", abr: "", mon: null},
{id: 99, hun: "Sarkantyús frankolin", ltn: "Pternistis bicalcaratus", abr: "", mon: null},
{id: 100, hun: "Fogoly", ltn: "Perdix perdix", abr: "fogo", mon: "333333333333"},
{id: 101, hun: "Fürj", ltn: "Coturnix coturnix", abr: "furj", mon: "113333333311"},
{id: 102, hun: "Királyfácán", ltn: "Syrmaticus reevesii", abr: "", mon: null},
{id: 103, hun: "Fácán", ltn: "Phasianus colchicus", abr: "faca", mon: "333333333333"},
{id: 104, hun: "Aranyfácán", ltn: "Chrysolophus pictus", abr: "", mon: null},
{id: 105, hun: "Gyémántfácán", ltn: "Chrysolophus amherstiae", abr: "", mon: null},
{id: 106, hun: "Estifecske", ltn: "Chordeiles minor", abr: "", mon: null},
{id: 107, hun: "Rozsdásnyakú lappantyú", ltn: "Caprimulgus ruficollis", abr: "", mon: null},
{id: 108, hun: "Lappantyú", ltn: "Caprimulgus europaeus", abr: "lapp", mon: "111333333211"},
{id: 109, hun: "Sivatagi lappantyú", ltn: "Caprimulgus aegyptius", abr: "", mon: null},
{id: 110, hun: "Núbiai lappantyú", ltn: "Caprimulgus nubicus", abr: "", mon: null},
{id: 111, hun: "Aranylappantyú", ltn: "Caprimulgus eximius", abr: "", mon: null},
{id: 112, hun: "Sertefarkú sarlósfecske", ltn: "Hirundapus caudacutus", abr: "", mon: null},
{id: 113, hun: "Kéménysarlósfecske", ltn: "Chaetura pelagica", abr: "", mon: null},
{id: 114, hun: "Afrikai pálmasarlósfecske", ltn: "Cypsiurus parvus", abr: "", mon: null},
{id: 115, hun: "Havasi sarlósfecske", ltn: "Tachymarptis melba", abr: "hvsf", mon: "111111111111"},
{id: 116, hun: "Zöld-foki-szigeteki sarlósfecske", ltn: "Apus alexandri", abr: "", mon: null},
{id: 117, hun: "Sarlósfecske", ltn: "Apus apus", abr: "safe,slfc", mon: "111333333211"},
{id: 118, hun: "Egyszínű sarlósfecske", ltn: "Apus unicolor", abr: "", mon: null},
{id: 119, hun: "Halvány sarlósfecske", ltn: "Apus pallidus", abr: "hlsf", mon: "111111111111"},
{id: 120, hun: "Keleti sarlósfecske", ltn: "Apus pacificus", abr: "", mon: null},
{id: 121, hun: "Kis sarlósfecske", ltn: "Apus affinis", abr: "", mon: null},
{id: 122, hun: "Kaffer sarlósfecske", ltn: "Apus caffer", abr: "", mon: null},
{id: 123, hun: "Túzok", ltn: "Otis tarda", abr: "tuzo", mon: "222222222222"},
{id: 124, hun: "Arab túzok", ltn: "Ardeotis arabs", abr: "", mon: null},
{id: 125, hun: "Galléros túzok", ltn: "Chlamydotis undulata", abr: "", mon: null},
{id: 126, hun: "Pettyes túzok", ltn: "Chlamydotis macqueenii", abr: "", mon: null},
{id: 127, hun: "Száheli túzok", ltn: "Neotis nuba", abr: "", mon: null},
{id: 128, hun: "Reznek", ltn: "Tetrax tetrax", abr: "rezn", mon: "111111111111"},
{id: 129, hun: "Szenegáli bozótkakukk", ltn: "Centropus senegalensis", abr: "", mon: null},
{id: 130, hun: "Pettyes kakukk", ltn: "Clamator glandarius", abr: "ptkk", mon: "111111111111"},
{id: 131, hun: "Szarkakakukk", ltn: "Clamator jacobinus", abr: "", mon: null},
{id: 132, hun: "Sárgacsőrű esőkakukk", ltn: "Coccyzus americanus", abr: "", mon: null},
{id: 133, hun: "Feketecsőrű esőkakukk", ltn: "Coccyzus erythropthalmus", abr: "", mon: null},
{id: 134, hun: "Koel", ltn: "Eudynamys scolopaceus", abr: "", mon: null},
{id: 135, hun: "Rezes fénykakukk", ltn: "Chrysococcyx caprius", abr: "", mon: null},
{id: 136, hun: "Keleti kakukk", ltn: "Cuculus optatus", abr: "", mon: null},
{id: 137, hun: "Kakukk", ltn: "Cuculus canorus", abr: "kaku", mon: "112333333211"},
{id: 138, hun: "Talpastyúk", ltn: "Syrrhaptes paradoxus", abr: "tpty", mon: "111111111111"},
{id: 139, hun: "Nyílfarkú pusztaityúk", ltn: "Pterocles alchata", abr: "", mon: null},
{id: 140, hun: "Barnahasú pusztaityúk", ltn: "Pterocles exustus", abr: "bpty", mon: "111111111111"},
{id: 141, hun: "Pettyes pusztaityúk", ltn: "Pterocles senegallus", abr: "", mon: null},
{id: 142, hun: "Feketehasú pusztaityúk", ltn: "Pterocles orientalis", abr: "", mon: null},
{id: 143, hun: "Koronás pusztaityúk", ltn: "Pterocles coronatus", abr: "", mon: null},
{id: 144, hun: "Csíkos pusztaityúk", ltn: "Pterocles lichtensteinii", abr: "", mon: null},
{id: 145, hun: "Szirti galamb", ltn: "Columba livia", abr: "", mon: null},
{id: 146, hun: "Parlagi galamb", ltn: "Columba livia f. domestica", abr: "plga,plgb", mon: "000000000000"},
{id: 147, hun: "Pettyesszárnyú galamb", ltn: "Columba guinea", abr: "", mon: null},
{id: 148, hun: "Kék galamb", ltn: "Columba oenas", abr: "kkga,kkgl", mon: "333333333333"},
{id: 149, hun: "Sárgaszemű galamb", ltn: "Columba eversmanni", abr: "", mon: null},
{id: 150, hun: "Örvös galamb", ltn: "Columba palumbus", abr: "orga,orgb", mon: "233333333332"},
{id: 151, hun: "Madeirai babérgalamb", ltn: "Columba trocaz", abr: "", mon: null},
{id: 152, hun: "Szürkefejű babérgalamb", ltn: "Columba bollii", abr: "", mon: null},
{id: 153, hun: "Fehérfarkú babérgalamb", ltn: "Columba junoniae", abr: "", mon: null},
{id: 154, hun: "Vadgerle", ltn: "Streptopelia turtur", abr: "vger,vdgl", mon: "112333333311"},
{id: 155, hun: "Keleti gerle", ltn: "Streptopelia orientalis", abr: "kger,ktgl", mon: "111111111111"},
{id: 156, hun: "Balkáni gerle", ltn: "Streptopelia decaocto", abr: "bage,bkge,bkgl", mon: "333333333333"},
{id: 157, hun: "Kacagó gerle", ltn: "Streptopelia roseogrisea", abr: "", mon: null},
{id: 158, hun: "Pápaszemes gerle", ltn: "Streptopelia decipiens", abr: "", mon: null},
{id: 159, hun: "Pálmagerle", ltn: "Spilopelia senegalensis", abr: "", mon: null},
{id: 160, hun: "Álarcos gerle", ltn: "Oena capensis", abr: "", mon: null},
{id: 161, hun: "Sirató gerle", ltn: "Zenaida macroura", abr: "", mon: null},
{id: 162, hun: "Sárgahasú lombgalamb", ltn: "Treron waalia", abr: "", mon: null},
{id: 163, hun: "Guvat", ltn: "Rallus aquaticus", abr: "guva", mon: "333333333333"},
{id: 164, hun: "Afrikai haris", ltn: "Crecopsis egregia", abr: "", mon: null},
{id: 165, hun: "Haris", ltn: "Crex crex", abr: "hari", mon: "111333333111"},
{id: 166, hun: "Álarcos vízicsibe", ltn: "Porzana carolina", abr: "", mon: null},
{id: 167, hun: "Pettyes vízicsibe", ltn: "Porzana porzana", abr: "pvcs", mon: "113333333311"},
{id: 168, hun: "Törpevízityúk", ltn: "Paragallinula angulata", abr: "", mon: null},
{id: 169, hun: "Vízityúk", ltn: "Gallinula chloropus", abr: "vzty", mon: "333333333333"},
{id: 170, hun: "Szárcsa", ltn: "Fulica atra", abr: "szac,szcs", mon: "333333333333"},
{id: 171, hun: "Bütykös szárcsa", ltn: "Fulica cristata", abr: "", mon: null},
{id: 172, hun: "Gyűrűscsőrű szárcsa", ltn: "Fulica americana", abr: "", mon: null},
{id: 173, hun: "Afrikai szultántyúk", ltn: "Porphyrio alleni", abr: "", mon: null},
{id: 174, hun: "Amerikai szultántyúk", ltn: "Porphyrio martinica", abr: "", mon: null},
{id: 175, hun: "Nyugati kékfú", ltn: "Porphyrio porphyrio", abr: "", mon: null},
{id: 176, hun: "Zöldhátú kékfú", ltn: "Porphyrio madagascariensis", abr: "", mon: null},
{id: 177, hun: "Szürkefejű kékfú", ltn: "Porphyrio poliocephalus", abr: "", mon: "111111111111"},
{id: 178, hun: "Törpevízicsibe", ltn: "Zapornia pusilla", abr: "tvcs", mon: "111111111111"},
{id: 179, hun: "Kis vízicsibe", ltn: "Zapornia parva", abr: "kvcs", mon: "113333333311"},
{id: 180, hun: "Csíkos vízicsibe", ltn: "Aenigmatolimnas marginalis", abr: "", mon: null},
{id: 181, hun: "Fehérmellű lápityúk", ltn: "Amaurornis phoenicurus", abr: "", mon: null},
{id: 182, hun: "Hódaru", ltn: "Leucogeranus leucogeranus", abr: "", mon: null},
{id: 183, hun: "Kanadai daru", ltn: "Antigone canadensis", abr: "", mon: "000000000000"},
{id: 184, hun: "Pártás daru", ltn: "Grus virgo", abr: "ptdr", mon: "111111111111"},
{id: 185, hun: "Daru", ltn: "Grus grus", abr: "daru", mon: "333333333333"},
{id: 186, hun: "Kis vöcsök", ltn: "Tachybaptus ruficollis", abr: "ksvo,ksvc", mon: "333333333333"},
{id: 187, hun: "Gyűrűscsőrű vöcsök", ltn: "Podilymbus podiceps", abr: "", mon: null},
{id: 188, hun: "Vörösnyakú vöcsök", ltn: "Podiceps grisegena", abr: "vnvo,vnvc", mon: "222222222222"},
{id: 189, hun: "Búbos vöcsök", ltn: "Podiceps cristatus", abr: "buvo,bbvo,bbvc", mon: "333333333333"},
{id: 190, hun: "Füles vöcsök", ltn: "Podiceps auritus", abr: "flvo,flvc", mon: "111111111111"},
{id: 191, hun: "Feketenyakú vöcsök", ltn: "Podiceps nigricollis", abr: "fnvo,fnvc", mon: "223333333332"},
{id: 192, hun: "Rózsás flamingó", ltn: "Phoenicopterus roseus", abr: "rzfl", mon: "111111111111"},
{id: 193, hun: "Kis flamingó", ltn: "Phoeniconaias minor", abr: "", mon: "000000000000"},
{id: 194, hun: "Guvatfürj", ltn: "Turnix sylvaticus", abr: "", mon: null},
{id: 195, hun: "Ugartyúk", ltn: "Burhinus oedicnemus", abr: "ugty", mon: "112333333211"},
{id: 196, hun: "Száheli ugartyúk", ltn: "Burhinus senegalensis", abr: "", mon: null},
{id: 197, hun: "Szerecsen-csigaforgató", ltn: "Haematopus moquini", abr: "", mon: null},
{id: 198, hun: "Csigaforgató", ltn: "Haematopus ostralegus", abr: "csfg", mon: "111111111111"},
{id: 199, hun: "Gólyatöcs", ltn: "Himantopus himantopus", abr: "gtcs", mon: "113333333211"},
{id: 200, hun: "Gulipán", ltn: "Recurvirostra avosetta", abr: "guli", mon: "113333333332"},
{id: 201, hun: "Bíbic", ltn: "Vanellus vanellus", abr: "bibi", mon: "333333333333"},
{id: 202, hun: "Tüskés bíbic", ltn: "Vanellus spinosus", abr: "tsbb", mon: "111111111111"},
{id: 203, hun: "Sisakos bibic", ltn: "Vanellus tectus", abr: "", mon: null},
{id: 204, hun: "Szürkefejű bíbic", ltn: "Vanellus cinereus", abr: "", mon: null},
{id: 205, hun: "Bibircses bíbic", ltn: "Vanellus indicus", abr: "", mon: null},
{id: 206, hun: "Lilebíbic", ltn: "Vanellus gregarius", abr: "llbb", mon: "111111111111"},
{id: 207, hun: "Fehérfarkú lilebíbic", ltn: "Vanellus leucurus", abr: "flbb", mon: "111111111111"},
{id: 208, hun: "Aranylile", ltn: "Pluvialis apricaria", abr: "arli,arll", mon: "223332233322"},
{id: 209, hun: "Ázsiai pettyeslile", ltn: "Pluvialis fulva", abr: "azpl", mon: "111111111111"},
{id: 210, hun: "Amerikai pettyeslile", ltn: "Pluvialis dominica", abr: "ampl", mon: "111111111111"},
{id: 211, hun: "Pettyeslile faj", ltn: "Pluvialis dominica/fulva", abr: "", mon: "111111111111"},
{id: 212, hun: "Ezüstlile", ltn: "Pluvialis squatarola", abr: "ezli,ezll", mon: "222233333332"},
{id: 213, hun: "Parti lile", ltn: "Charadrius hiaticula", abr: "ptli,ptll", mon: "113333333321"},
{id: 214, hun: "Kanadai lile", ltn: "Charadrius semipalmatus", abr: "", mon: null},
{id: 215, hun: "Kis lile", ltn: "Charadrius dubius", abr: "ksli,ksll", mon: "113333333321"},
{id: 216, hun: "Ékfarkú lile", ltn: "Charadrius vociferus", abr: "efli,efll", mon: "111111111111"},
{id: 217, hun: "Apró lile", ltn: "Charadrius pecuarius", abr: "", mon: null},
{id: 218, hun: "Szalagos lile", ltn: "Charadrius tricollaris", abr: "", mon: null},
{id: 219, hun: "Széki lile", ltn: "Charadrius alexandrinus", abr: "szli,szll", mon: "112222222211"},
{id: 220, hun: "Tibeti lile", ltn: "Charadrius mongolus", abr: "", mon: null},
{id: 221, hun: "Sivatagi lile", ltn: "Charadrius leschenaultii", abr: "svli,svll", mon: "111111111111"},
{id: 222, hun: "Sztyeppi lile", ltn: "Charadrius asiaticus", abr: "", mon: "000000000000"},
{id: 223, hun: "Barnaszárnyú lile", ltn: "Charadrius veredus", abr: "", mon: null},
{id: 224, hun: "Havasi lile", ltn: "Charadrius morinellus", abr: "hvli,hvll", mon: "111111111111"},
{id: 225, hun: "Krokodilmadár", ltn: "Pluvianus aegyptius", abr: "", mon: null},
{id: 226, hun: "Guvatszalonka", ltn: "Rostratula benghalensis", abr: "", mon: null},
{id: 227, hun: "Hosszúfarkú cankó", ltn: "Bartramia longicauda", abr: "hfck", mon: "111111111111"},
{id: 228, hun: "Kis póling", ltn: "Numenius phaeopus", abr: "kspo,kspl", mon: "113333333221"},
{id: 229, hun: "Kanadai póling", ltn: "Numenius hudsonicus", abr: "", mon: null},
{id: 230, hun: "Törpepóling", ltn: "Numenius minutus", abr: "", mon: null},
{id: 231, hun: "Eszkimó póling", ltn: "Numenius borealis", abr: "", mon: null},
{id: 232, hun: "Vékonycsőrű póling", ltn: "Numenius tenuirostris", abr: "vcpo,vcpl", mon: "111111111111"},
{id: 233, hun: "Nagy póling", ltn: "Numenius arquata", abr: "nppo,ngpl", mon: "333333333333"},
{id: 234, hun: "Kis goda", ltn: "Limosa lapponica", abr: "ksgo,ksgd", mon: "111111111111"},
{id: 235, hun: "Nagy goda", ltn: "Limosa limosa", abr: "nggo,nggd", mon: "123333333322"},
{id: 236, hun: "Feketeszárnyú goda", ltn: "Limosa haemastica", abr: "", mon: null},
{id: 237, hun: "Kőforgató", ltn: "Arenaria interpres", abr: "kfor", mon: "111122222111"},
{id: 238, hun: "Nagy partfutó", ltn: "Calidris tenuirostris", abr: "", mon: null},
{id: 239, hun: "Sarki partfutó", ltn: "Calidris canutus", abr: "skpf", mon: "111111111111"},
{id: 240, hun: "Pajzsoscankó", ltn: "Calidris pugnax", abr: "pzck", mon: "233333333332"},
{id: 241, hun: "Sárjáró", ltn: "Calidris falcinellus", abr: "sarj,srjr", mon: "111111111111"},
{id: 242, hun: "Hegyesfarkú partfutó", ltn: "Calidris acuminata", abr: "hfpf", mon: "111111111111"},
{id: 243, hun: "Töcspartfutó", ltn: "Calidris himantopus", abr: "tcpf", mon: "111111111111"},
{id: 244, hun: "Sarlós partfutó", ltn: "Calidris ferruginea", abr: "slpf", mon: "112333333311"},
{id: 245, hun: "Temminck-partfutó", ltn: "Calidris temminckii", abr: "tmpf", mon: "112333333211"},
{id: 246, hun: "Hosszúujjú partfutó", ltn: "Calidris subminuta", abr: "", mon: null},
{id: 247, hun: "Rozsdástorkú partfutó", ltn: "Calidris ruficollis", abr: "", mon: null},
{id: 248, hun: "Fenyérfutó", ltn: "Calidris alba", abr: "fnft", mon: "111111111111"},
{id: 249, hun: "Havasi partfutó", ltn: "Calidris alpina", abr: "hvpf", mon: "223333333332"},
{id: 250, hun: "Tengeri partfutó", ltn: "Calidris maritima", abr: "tgpf", mon: "111111111111"},
{id: 251, hun: "Baird-partfutó", ltn: "Calidris bairdii", abr: "bdpf", mon: "111111111111"},
{id: 252, hun: "Apró partfutó", ltn: "Calidris minuta", abr: "appf", mon: "222333333322"},
{id: 253, hun: "Törpepartfutó", ltn: "Calidris minutilla", abr: "", mon: null},
{id: 254, hun: "Bonaparte-partfutó", ltn: "Calidris fuscicollis", abr: "bnpf", mon: "111111111111"},
{id: 255, hun: "Cankópartfutó", ltn: "Calidris subruficollis", abr: "ckpf", mon: "111111111111"},
{id: 256, hun: "Vándorpartfutó", ltn: "Calidris melanotos", abr: "vdpf", mon: "111111111111"},
{id: 257, hun: "Kis partfutó", ltn: "Calidris pusilla", abr: "kspf", mon: "111111111111"},
{id: 258, hun: "Alaszkai partfutó", ltn: "Calidris mauri", abr: "", mon: null},
{id: 259, hun: "Hosszúcsőrű cankógoda", ltn: "Limnodromus scolopaceus", abr: "hccg", mon: "111111111111"},
{id: 260, hun: "Rövidcsőrű cankógoda", ltn: "Limnodromus griseus", abr: "", mon: null},
{id: 261, hun: "Erdei szalonka", ltn: "Scolopax rusticola", abr: "ersz", mon: "223322222332"},
{id: 262, hun: "Koboldszalonka", ltn: "Scolopax minor", abr: "", mon: null},
{id: 263, hun: "Kis sárszalonka", ltn: "Lymnocryptes minimus", abr: "kssz", mon: "111111111111"},
{id: 264, hun: "Hegyesfarkú sárszalonka", ltn: "Gallinago stenura", abr: "", mon: null},
{id: 265, hun: "Tajgasárszalonka", ltn: "Gallinago megala", abr: "", mon: null},
{id: 266, hun: "Nagy sárszalonka", ltn: "Gallinago media", abr: "nssz", mon: "111111111111"},
{id: 267, hun: "Sárszalonka", ltn: "Gallinago gallinago", abr: "srsz", mon: "223333333332"},
{id: 268, hun: "Amerikai sárszalonka", ltn: "Gallinago delicata", abr: "", mon: null},
{id: 269, hun: "Terekcankó", ltn: "Xenus cinereus", abr: "trck", mon: "111111111111"},
{id: 270, hun: "Wilson-víztaposó", ltn: "Phalaropus tricolor", abr: "wlvt", mon: "111111111111"},
{id: 271, hun: "Vékonycsőrű víztaposó", ltn: "Phalaropus lobatus", abr: "vcvt", mon: "111111111111"},
{id: 272, hun: "Laposcsőrű víztaposó", ltn: "Phalaropus fulicarius", abr: "lcvt", mon: "111111111111"},
{id: 273, hun: "Billegetőcankó", ltn: "Actitis hypoleucos", abr: "bcan,blck", mon: "223333333322"},
{id: 274, hun: "Pettyes billegetőcankó", ltn: "Actitis macularius", abr: "", mon: null},
{id: 275, hun: "Erdei cankó", ltn: "Tringa ochropus", abr: "erck", mon: "333333333333"},
{id: 276, hun: "Remetecankó", ltn: "Tringa solitaria", abr: "", mon: null},
{id: 277, hun: "Szibériai vándorcankó", ltn: "Tringa brevipes", abr: "", mon: null},
{id: 278, hun: "Sárgalábú cankó", ltn: "Tringa flavipes", abr: "slck", mon: "111111111111"},
{id: 279, hun: "Lármás cankó", ltn: "Tringa semipalmata", abr: "", mon: null},
{id: 280, hun: "Piroslábú cankó", ltn: "Tringa totanus", abr: "plck,plca", mon: "133333333221"},
{id: 281, hun: "Tavi cankó", ltn: "Tringa stagnatilis", abr: "tvck", mon: "111222222111"},
{id: 282, hun: "Réti cankó", ltn: "Tringa glareola", abr: "rtck", mon: "113333333321"},
{id: 283, hun: "Füstös cankó", ltn: "Tringa erythropus", abr: "ftck", mon: "223333333332"},
{id: 284, hun: "Szürke cankó", ltn: "Tringa nebularia", abr: "szck", mon: "223333333322"},
{id: 285, hun: "Mocsári cankó", ltn: "Tringa melanoleuca", abr: "", mon: null},
{id: 286, hun: "Gémlile", ltn: "Dromas ardeola", abr: "", mon: null},
{id: 287, hun: "Futómadár", ltn: "Cursorius cursor", abr: "", mon: null},
{id: 288, hun: "Temminck-futómadár", ltn: "Cursorius temminckii", abr: "", mon: null},
{id: 289, hun: "Székicsér", ltn: "Glareola pratincola", abr: "szkc", mon: "111222222211"},
{id: 290, hun: "Keleti székicsér", ltn: "Glareola maldivarum", abr: "klsc", mon: "111111111111"},
{id: 291, hun: "Feketeszárnyú székicsér", ltn: "Glareola nordmanni", abr: "fssc", mon: "111111111111"},
{id: 292, hun: "Barna noddi", ltn: "Anous stolidus", abr: "", mon: null},
{id: 293, hun: "Afrikai  ollóscsőrűmadár", ltn: "Rynchops flavirostris", abr: "", mon: null},
{id: 294, hun: "Csüllő", ltn: "Rissa tridactyla", abr: "csul", mon: "111111111111"},
{id: 295, hun: "Hósirály", ltn: "Pagophila eburnea", abr: "", mon: null},
{id: 296, hun: "Fecskesirály", ltn: "Xema sabini", abr: "fksr", mon: "111111111111"},
{id: 297, hun: "Vékonycsőrű sirály", ltn: "Chroicocephalus genei", abr: "vcsr", mon: "111111111111"},
{id: 298, hun: "Bonaparte-sirály", ltn: "Chroicocephalus philadelphia", abr: "bnsr", mon: "000000000000"},
{id: 299, hun: "Barnafejű sirály", ltn: "Chroicocephalus brunnicephalus", abr: "", mon: null},
{id: 300, hun: "Dankasirály", ltn: "Chroicocephalus ridibundus", abr: "dasi,dksr", mon: "333333333333"},
{id: 301, hun: "Szürkefejű sirály", ltn: "Chroicocephalus cirrocephalus", abr: "", mon: null},
{id: 302, hun: "Kis sirály", ltn: "Hydrocoloeus minutus", abr: "kssi,kssr", mon: "223332333333"},
{id: 303, hun: "Rózsás sirály", ltn: "Rhodostethia rosea", abr: "", mon: null},
{id: 304, hun: "Kacagó sirály", ltn: "Leucophaeus atricilla", abr: "", mon: null},
{id: 305, hun: "Prérisirály", ltn: "Leucophaeus pipixcan", abr: "prsr", mon: "111111111111"},
{id: 306, hun: "Mongol sirály", ltn: "Ichthyaetus relictus", abr: "", mon: null},
{id: 307, hun: "Korallsirály", ltn: "Ichthyaetus audouinii", abr: "krsr", mon: "000000000000"},
{id: 308, hun: "Szerecsensirály", ltn: "Ichthyaetus melanocephalus", abr: "szsi,szsr,snsr", mon: "223333333222"},
{id: 309, hun: "Halászsirály", ltn: "Ichthyaetus ichthyaetus", abr: "hlsr", mon: "111111111111"},
{id: 310, hun: "Pápaszemes sirály", ltn: "Ichthyaetus leucophthalmus", abr: "", mon: null},
{id: 311, hun: "Füstös sirály", ltn: "Ichthyaetus hemprichii", abr: "", mon: null},
{id: 312, hun: "Viharsirály", ltn: "Larus canus", abr: "vhsi,vhsr", mon: "333322223333"},
{id: 313, hun: "Rövidcsőrű sirály", ltn: "Larus brachyrhynchus", abr: "", mon: null},
{id: 314, hun: "Gyűrűscsőrű sirály", ltn: "Larus delawarensis", abr: "gcsr", mon: "111111111111"},
{id: 315, hun: "Dolmányos sirály", ltn: "Larus marinus", abr: "dmsr", mon: "111111111111"},
{id: 316, hun: "Déli sirály", ltn: "Larus dominicanus", abr: "", mon: null},
{id: 317, hun: "Bering-tengeri sirály", ltn: "Larus glaucescens", abr: "", mon: null},
{id: 318, hun: "Jeges sirály", ltn: "Larus hyperboreus", abr: "jgsr", mon: "111111111111"},
{id: 319, hun: "Sarki sirály", ltn: "Larus glaucoides", abr: "sksr", mon: "111111111111"},
{id: 320, hun: "Eszkimó sirály", ltn: "Larus glaucoides thayeri", abr: "", mon: null},
{id: 321, hun: "Ezüstsirály", ltn: "Larus argentatus", abr: "ezsr", mon: "111111111111"},
{id: 322, hun: "Amerikai ezüstsirály", ltn: "Larus smithsonianus", abr: "", mon: null},
{id: 323, hun: "Szibériai ezüstsirály", ltn: "Larus vegae", abr: "", mon: null},
{id: 324, hun: "Sztyeppi sirály", ltn: "Larus cachinnans", abr: "stsr,sisr", mon: "333333333333"},
{id: 325, hun: "Sárgalábú sirály", ltn: "Larus michahellis", abr: "slsi,slsr", mon: "333333333333"},
{id: 326, hun: "Örmény sirály", ltn: "Larus armenicus", abr: "orsr", mon: "111111111111"},
{id: 327, hun: "Kamcsatkai sirály", ltn: "Larus schistisagus", abr: "", mon: null},
{id: 328, hun: "Heringsirály", ltn: "Larus fuscus", abr: "hrsr", mon: "111111111111"},
{id: 329, hun: "Világoshátú heringsirály", ltn: "Larus fuscus graellsii/intermedius", abr: "vhhs", mon: "111111111111"},
{id: 330, hun: "Szibériai heringsirály", ltn: "Larus fuscus heuglini", abr: "szhs", mon: "111111111111"},
{id: 331, hun: "Kacagócsér", ltn: "Gelochelidon nilotica", abr: "kccs", mon: "111111111111"},
{id: 332, hun: "Lócsér", ltn: "Hydroprogne caspia", abr: "locs", mon: "111111111111"},
{id: 333, hun: "Királycsér", ltn: "Thalasseus maximus", abr: "", mon: null},
{id: 334, hun: "Üstökös csér", ltn: "Thalasseus bergii", abr: "", mon: null},
{id: 335, hun: "Bengáli csér", ltn: "Thalasseus bengalensis", abr: "", mon: null},
{id: 336, hun: "Kontyos csér", ltn: "Thalasseus albididorsalis", abr: "", mon: null},
{id: 337, hun: "Kenti csér", ltn: "Thalasseus sandvicensis", abr: "ktcs", mon: "111111111111"},
{id: 338, hun: "Cabot-csér", ltn: "Thalasseus acuflavidus", abr: "", mon: null},
{id: 339, hun: "Pompás csér", ltn: "Thalasseus elegans", abr: "", mon: null},
{id: 340, hun: "Kis csér", ltn: "Sternula albifrons", abr: "kscs", mon: "111111111111"},
{id: 341, hun: "Arab törpecsér", ltn: "Sternula saundersi", abr: "", mon: null},
{id: 342, hun: "Karib csér", ltn: "Sternula antillarum", abr: "", mon: null},
{id: 343, hun: "Bering-tengeri csér", ltn: "Onychoprion aleuticus", abr: "", mon: null},
{id: 344, hun: "Álarcos csér", ltn: "Onychoprion anaethetus", abr: "", mon: null},
{id: 345, hun: "Füstös csér", ltn: "Onychoprion fuscatus", abr: "", mon: null},
{id: 346, hun: "Rózsás csér", ltn: "Sterna dougallii", abr: "", mon: null},
{id: 347, hun: "Küszvágó csér", ltn: "Sterna hirundo", abr: "kucs,kvcs", mon: "112333333311"},
{id: 348, hun: "Fehérarcú csér", ltn: "Sterna repressa", abr: "", mon: null},
{id: 349, hun: "Sarki csér", ltn: "Sterna paradisaea", abr: "skcs", mon: "111111111111"},
{id: 350, hun: "Tavi csér", ltn: "Sterna forsteri", abr: "", mon: null},
{id: 351, hun: "Fattyúszerkő", ltn: "Chlidonias hybrida", abr: "fasz,ftsz", mon: "112333333322"},
{id: 352, hun: "Fehérszárnyú szerkő", ltn: "Chlidonias leucopterus", abr: "fssz", mon: "112333333211"},
{id: 353, hun: "Kormos szerkő", ltn: "Chlidonias niger", abr: "kmsz,kosz", mon: "112333333311"},
{id: 354, hun: "Délsarki halfarkas", ltn: "Stercorarius maccormicki", abr: "", mon: null},
{id: 355, hun: "Nagy halfarkas", ltn: "Stercorarius skua", abr: "nghf", mon: "111111111111"},
{id: 356, hun: "Szélesfarkú halfarkas", ltn: "Stercorarius pomarinus", abr: "sfhf", mon: "111111111111"},
{id: 357, hun: "Ékfarkú halfarkas", ltn: "Stercorarius parasiticus", abr: "efhf", mon: "111111111111"},
{id: 358, hun: "Nyílfarkú halfarkas", ltn: "Stercorarius longicaudus", abr: "nfhf", mon: "111111111111"},
{id: 359, hun: "Halfarkas faj", ltn: "Stercorarius sp.", abr: "", mon: "000000000000"},
{id: 360, hun: "Alkabukó", ltn: "Alle alle", abr: "", mon: null},
{id: 361, hun: "Vastagcsőrű lumma", ltn: "Uria lomvia", abr: "", mon: null},
{id: 362, hun: "Lumma", ltn: "Uria aalge", abr: "", mon: null},
{id: 363, hun: "Alka", ltn: "Alca torda", abr: "alka", mon: "111111111111"},
{id: 364, hun: "Fekete lumma", ltn: "Cepphus grylle", abr: "", mon: null},
{id: 365, hun: "Hosszúcsőrű törpealka", ltn: "Brachyramphus perdix", abr: "", mon: null},
{id: 366, hun: "Ezüstalka", ltn: "Synthliboramphus antiquus", abr: "", mon: null},
{id: 367, hun: "Papagájalka", ltn: "Aethia psittacula", abr: "", mon: null},
{id: 368, hun: "Bóbitás alka", ltn: "Aethia cristatella", abr: "", mon: null},
{id: 369, hun: "Lunda", ltn: "Fratercula arctica", abr: "lund", mon: "111111111111"},
{id: 370, hun: "Kontyos lunda", ltn: "Fratercula cirrhata", abr: "", mon: null},
{id: 371, hun: "Vöröscsőrű trópusimadár", ltn: "Phaethon aethereus", abr: "", mon: null},
{id: 372, hun: "Fehérfarkú trópusimadár", ltn: "Phaethon lepturus", abr: "", mon: null},
{id: 373, hun: "Északi búvár", ltn: "Gavia stellata", abr: "ebuv,esbu,esbv", mon: "221111111122"},
{id: 374, hun: "Sarki búvár", ltn: "Gavia arctica", abr: "skbv", mon: "221111111122"},
{id: 375, hun: "Alaszkai búvár", ltn: "Gavia pacifica", abr: "", mon: null},
{id: 376, hun: "Jeges búvár", ltn: "Gavia immer", abr: "jgbv", mon: "111111111111"},
{id: 377, hun: "Fehércsőrű búvár", ltn: "Gavia adamsii", abr: "fcbv", mon: "000000000000"},
{id: 378, hun: "Wilson-viharfecske", ltn: "Oceanites oceanicus", abr: "", mon: null},
{id: 379, hun: "Fehérarcú viharfecske", ltn: "Pelagodroma marina", abr: "", mon: null},
{id: 380, hun: "Feketehasú fregattfecske", ltn: "Fregetta tropica", abr: "", mon: null},
{id: 381, hun: "Gough-szigeti albatrosz", ltn: "Diomedea dabbenena", abr: "", mon: null},
{id: 382, hun: "Dolmányos albatrosz", ltn: "Thalassarche melanophris", abr: "", mon: null},
{id: 383, hun: "Tasmániai albatrosz", ltn: "Thalassarche cauta", abr: "", mon: null},
{id: 384, hun: "Sárgaorrú albatrosz", ltn: "Thalassarche chlororhynchos", abr: "", mon: null},
{id: 385, hun: "Viharfecske", ltn: "Hydrobates pelagicus", abr: "", mon: null},
{id: 386, hun: "Madeirai viharfecske", ltn: "Oceanodroma castro", abr: "", mon: null},
{id: 387, hun: "Monteiro-viharfecske", ltn: "Oceanodroma monteiroi", abr: "", mon: null},
{id: 388, hun: "Zöld-foki-szigeteki viharfecske", ltn: "Oceanodroma jabejabe", abr: "", mon: null},
{id: 389, hun: "Koreai viharfecske", ltn: "Oceanodroma monorhis", abr: "", mon: null},
{id: 390, hun: "Villás viharfecske", ltn: "Oceanodroma leucorhoa", abr: "", mon: null},
{id: 391, hun: "Déli óriáshojsza", ltn: "Macronectes giganteus", abr: "", mon: null},
{id: 392, hun: "Északi sirályhojsza", ltn: "Fulmarus glacialis", abr: "", mon: null},
{id: 393, hun: "Galambhojsza", ltn: "Daption capense", abr: "", mon: null},
{id: 394, hun: "Csuklyás viharmadár", ltn: "Pterodroma incerta", abr: "", mon: null},
{id: 395, hun: "Selymes viharmadár", ltn: "Pterodroma mollis", abr: "", mon: null},
{id: 396, hun: "Madeirai viharmadár", ltn: "Pterodroma madeira", abr: "", mon: null},
{id: 397, hun: "Zöld-foki-szigeteki viharmadár", ltn: "Pterodroma feae", abr: "", mon: null},
{id: 398, hun: "Desertasi viharmadár", ltn: "Pterodroma deserta", abr: "", mon: null},
{id: 399, hun: "Bermuda-szigeteki viharmadár", ltn: "Pterodroma cahow", abr: "", mon: null},
{id: 400, hun: "Karib viharmadár", ltn: "Pterodroma hasitata", abr: "", mon: null},
{id: 401, hun: "Hírnök viharmadár", ltn: "Pterodroma arminjoniana", abr: "", mon: null},
{id: 402, hun: "Fehértorkú viharmadár", ltn: "Procellaria aequinoctialis", abr: "", mon: null},
{id: 403, hun: "Csíkos vészmadár", ltn: "Calonectris leucomelas", abr: "", mon: null},
{id: 404, hun: "Mediterrán vészmadár", ltn: "Calonectris diomedea", abr: "", mon: null},
{id: 405, hun: "Cory-vészmadár", ltn: "Calonectris borealis", abr: "", mon: null},
{id: 406, hun: "Zöld-foki-szigeteki vészmadár", ltn: "Calonectris edwardsii", abr: "", mon: null},
{id: 407, hun: "Változékony vészmadár", ltn: "Ardenna pacifica", abr: "", mon: null},
{id: 408, hun: "Szürke vészmadár", ltn: "Ardenna grisea", abr: "", mon: null},
{id: 409, hun: "Vékonycsőrű vészmadár", ltn: "Ardenna tenuirostris", abr: "", mon: null},
{id: 410, hun: "Barna vészmadár", ltn: "Ardenna carneipes", abr: "", mon: null},
{id: 411, hun: "Nagy vészmadár", ltn: "Ardenna gravis", abr: "", mon: null},
{id: 412, hun: "Atlanti vészmadár", ltn: "Puffinus puffinus", abr: "", mon: null},
{id: 413, hun: "Bukdosó vészmadár", ltn: "Puffinus yelkouan", abr: "", mon: null},
{id: 414, hun: "Baleár-szigeteki vészmadár", ltn: "Puffinus mauretanicus", abr: "", mon: null},
{id: 415, hun: "Audubon-vészmadár", ltn: "Puffinus lherminieri", abr: "", mon: null},
{id: 416, hun: "Perzsa vészmadár", ltn: "Puffinus persicus", abr: "", mon: null},
{id: 417, hun: "Trópusi vészmadár", ltn: "Puffinus bailloni", abr: "", mon: null},
{id: 418, hun: "Kis vészmadár", ltn: "Puffinus baroli", abr: "", mon: null},
{id: 419, hun: "Boyd-vészmadár", ltn: "Puffinus boydi", abr: "", mon: null},
{id: 420, hun: "Szalagos szerecsenhojsza", ltn: "Bulweria bulwerii", abr: "", mon: null},
{id: 421, hun: "Egyszínű szerecsenhojsza", ltn: "Bulweria fallax", abr: "", mon: null},
{id: 422, hun: "Rózsás tantalusz", ltn: "Mycteria ibis", abr: "", mon: null},
{id: 423, hun: "Afrikai tátogatógólya", ltn: "Anastomus lamelligerus", abr: "", mon: null},
{id: 424, hun: "Fekete gólya", ltn: "Ciconia nigra", abr: "fkgo", mon: "113333333311"},
{id: 425, hun: "Fehér gólya", ltn: "Ciconia ciconia", abr: "fhgo", mon: "223333333222"},
{id: 426, hun: "Afrikai marabu", ltn: "Leptoptilos crumenifer", abr: "afmr", mon: "111111111111"},
{id: 427, hun: "Ascensioni fregattmadár", ltn: "Fregata aquila", abr: "", mon: null},
{id: 428, hun: "Pompás fregattmadár", ltn: "Fregata magnificens", abr: "", mon: null},
{id: 429, hun: "Kis fregattmadár", ltn: "Fregata ariel", abr: "", mon: null},
{id: 430, hun: "Szula", ltn: "Morus bassanus", abr: "", mon: null},
{id: 431, hun: "Fokföldi szula", ltn: "Morus capensis", abr: "", mon: null},
{id: 432, hun: "Álarcos szula", ltn: "Sula dactylatra", abr: "", mon: null},
{id: 433, hun: "Piroslábú szula", ltn: "Sula sula", abr: "", mon: null},
{id: 434, hun: "Barna szula", ltn: "Sula leucogaster", abr: "", mon: null},
{id: 435, hun: "Afrikai kígyónyakúmadár", ltn: "Anhinga rufa", abr: "", mon: null},
{id: 436, hun: "Kis kárókatona", ltn: "Microcarbo pygmaeus", abr: "kkor,ksko,kskk", mon: "333333333333"},
{id: 437, hun: "Afrikai kárókatona", ltn: "Microcarbo africanus", abr: "", mon: null},
{id: 438, hun: "Perzsa kárókatona", ltn: "Phalacrocorax nigrogularis", abr: "", mon: null},
{id: 439, hun: "Fehérmellű kárókatona", ltn: "Phalacrocorax lucidus", abr: "", mon: null},
{id: 440, hun: "Nagy kárókatona", ltn: "Phalacrocorax carbo", abr: "korm,ngkk", mon: "333333333333"},
{id: 441, hun: "Üstökös kárókatona", ltn: "Phalacrocorax aristotelis", abr: "", mon: null},
{id: 442, hun: "Füles kárókatona", ltn: "Phalacrocorax auritus", abr: "", mon: null},
{id: 443, hun: "Szent íbisz", ltn: "Threskiornis aethiopicus", abr: "", mon: null},
{id: 444, hun: "Tarvarjú", ltn: "Geronticus eremita", abr: "", mon: null},
{id: 445, hun: "Batla", ltn: "Plegadis falcinellus", abr: "batl", mon: "111222222211"},
{id: 446, hun: "Kanalasgém", ltn: "Platalea leucorodia", abr: "kngm,kgem", mon: "233333333322"},
{id: 447, hun: "Afrikai kanalasgém", ltn: "Platalea alba", abr: "afkg", mon: "000000000000"},
{id: 448, hun: "Bölömbika", ltn: "Botaurus stellaris", abr: "bolo", mon: "333333333333"},
{id: 449, hun: "Amerikai bölömbika", ltn: "Botaurus lentiginosus", abr: "", mon: null},
{id: 450, hun: "Amerikai törpegém", ltn: "Ixobrychus exilis", abr: "", mon: null},
{id: 451, hun: "Törpegém", ltn: "Ixobrychus minutus", abr: "tpgm,tgem", mon: "111333333211"},
{id: 452, hun: "Sárga törpegém", ltn: "Ixobrychus sinensis", abr: "", mon: null},
{id: 453, hun: "Vörhenyes törpegém", ltn: "Ixobrychus eurhythmus", abr: "", mon: null},
{id: 454, hun: "Szerecsentörpegém", ltn: "Ixobrychus sturmii", abr: "", mon: null},
{id: 455, hun: "Bakcsó", ltn: "Nycticorax nycticorax", abr: "bakc", mon: "223333333322"},
{id: 456, hun: "Sárgakoronás bakcsó", ltn: "Nyctanassa violacea", abr: "", mon: null},
{id: 457, hun: "Zöld gém", ltn: "Butorides virescens", abr: "", mon: null},
{id: 458, hun: "Mangrovegém", ltn: "Butorides striata", abr: "", mon: null},
{id: 459, hun: "Üstökösgém", ltn: "Ardeola ralloides", abr: "ugem,usgm", mon: "112333333211"},
{id: 460, hun: "Indiai  üstökösgém", ltn: "Ardeola grayii", abr: "", mon: null},
{id: 461, hun: "Kínai üstökösgém", ltn: "Ardeola bacchus", abr: "kugm", mon: "111111111111"},
{id: 462, hun: "Pásztorgém", ltn: "Bubulcus ibis", abr: "pgem,ptgm", mon: "111111111111"},
{id: 463, hun: "Keleti pásztorgém", ltn: "Bubulcus coromandus", abr: "", mon: null},
{id: 464, hun: "Szürke gém", ltn: "Ardea cinerea", abr: "sgem,szgm", mon: "333333333333"},
{id: 465, hun: "Királygém", ltn: "Ardea herodias", abr: "", mon: null},
{id: 466, hun: "Feketenyakú gém", ltn: "Ardea melanocephala", abr: "", mon: null},
{id: 467, hun: "Góliátgém", ltn: "Ardea goliath", abr: "", mon: null},
{id: 468, hun: "Vörös gém", ltn: "Ardea purpurea", abr: "vgem,vrgm", mon: "113333333211"},
{id: 469, hun: "Nagy kócsag", ltn: "Ardea alba", abr: "ngko,ngkc", mon: "333333333333"},
{id: 470, hun: "Középkócsag", ltn: "Ardea intermedia", abr: "", mon: null},
{id: 471, hun: "Haranggém", ltn: "Egretta ardesiaca", abr: "", mon: null},
{id: 472, hun: "Lagúnagém", ltn: "Egretta tricolor", abr: "", mon: null},
{id: 473, hun: "Kék gém", ltn: "Egretta caerulea", abr: "", mon: null},
{id: 474, hun: "Hókócsag", ltn: "Egretta thula", abr: "", mon: null},
{id: 475, hun: "Kis kócsag", ltn: "Egretta garzetta", abr: "ksko,kskc", mon: "113333333311"},
{id: 476, hun: "Zátonykócsag", ltn: "Egretta gularis", abr: "ztko,ztkc", mon: "111111111111"},
{id: 477, hun: "Rózsás gödény", ltn: "Pelecanus onocrotalus", abr: "rzgd", mon: "111111111111"},
{id: 478, hun: "Vörhenyes gödény", ltn: "Pelecanus rufescens", abr: "vhgd", mon: "111111111111"},
{id: 479, hun: "Borzas gödény", ltn: "Pelecanus crispus", abr: "bzgd", mon: "111111111111"},
{id: 480, hun: "Gödény faj", ltn: "Pelecanus sp.", abr: "", mon: "000000000000"},
{id: 481, hun: "Halászsas", ltn: "Pandion haliaetus", abr: "hsas,hlsa,hlss", mon: "112222222211"},
{id: 482, hun: "Kuhi", ltn: "Elanus caeruleus", abr: "kuhi", mon: "111111111111"},
{id: 483, hun: "Saskeselyű", ltn: "Gypaetus barbatus", abr: "sske,ssks", mon: null},
{id: 484, hun: "Dögkeselyű", ltn: "Neophron percnopterus", abr: "dgke,dgks", mon: "111111111111"},
{id: 485, hun: "Darázsölyv", ltn: "Pernis apivorus", abr: "doly,drov", mon: "111333333211"},
{id: 486, hun: "Bóbitás darázsölyv", ltn: "Pernis ptilorhynchus", abr: "", mon: null},
{id: 487, hun: "Fecskekánya", ltn: "Elanoides forficatus", abr: "", mon: null},
{id: 488, hun: "Csuklyás keselyű", ltn: "Necrosyrtes monachus", abr: "", mon: null},
{id: 489, hun: "Fehérhátú keselyű", ltn: "Gyps africanus", abr: "", mon: null},
{id: 490, hun: "Karvalykeselyű", ltn: "Gyps rueppelli", abr: "", mon: null},
{id: 491, hun: "Fakó keselyű", ltn: "Gyps fulvus", abr: "fkke,fkks", mon: "111111111111"},
{id: 492, hun: "Barátkeselyű", ltn: "Aegypius monachus", abr: "brke,brks", mon: "111111111111"},
{id: 493, hun: "Füles keselyű", ltn: "Torgos tracheliotos", abr: "", mon: null},
{id: 494, hun: "Kígyászölyv", ltn: "Circaetus gallicus", abr: "koly,kgov", mon: "112222222211"},
{id: 495, hun: "Bukázósas", ltn: "Terathopius ecaudatus", abr: "", mon: null},
{id: 496, hun: "Békászó sas", ltn: "Clanga pomarina", abr: "bksa,bkss", mon: "111222222111"},
{id: 497, hun: "Fekete sas", ltn: "Clanga clanga", abr: "fksa,fkss", mon: "111111111111"},
{id: 498, hun: "Gyíkászó sas", ltn: "Hieraaetus wahlbergi", abr: "", mon: null},
{id: 499, hun: "Törpesas", ltn: "Hieraaetus pennatus", abr: "tpsa,tpss", mon: "111111111111"},
{id: 500, hun: "Szavannasas", ltn: "Aquila rapax", abr: "", mon: null},
{id: 501, hun: "Pusztai sas", ltn: "Aquila nipalensis", abr: "ptsa,ptss", mon: "111111111111"},
{id: 502, hun: "Ibériai sas", ltn: "Aquila adalberti", abr: "", mon: null},
{id: 503, hun: "Parlagi sas", ltn: "Aquila heliaca", abr: "plsa,plss", mon: "222222222222"},
{id: 504, hun: "Szirti sas", ltn: "Aquila chrysaetos", abr: "szsa,szss", mon: "112222211111"},
{id: 505, hun: "Kaffer sas", ltn: "Aquila verreauxii", abr: "", mon: null},
{id: 506, hun: "Héjasas", ltn: "Aquila fasciata", abr: "hjsa,hjss", mon: "111111111111"},
{id: 507, hun: "Kis éneklőhéja", ltn: "Micronisus gabar", abr: "", mon: null},
{id: 508, hun: "Piroslábú éneklőhéja", ltn: "Melierax metabates", abr: "", mon: null},
{id: 509, hun: "Sikra", ltn: "Accipiter badius", abr: "", mon: null},
{id: 510, hun: "Kis héja", ltn: "Accipiter brevipes", abr: "kshj", mon: "111111111111"},
{id: 511, hun: "Karvaly", ltn: "Accipiter nisus", abr: "karv", mon: "333333333333"},
{id: 512, hun: "Héja", ltn: "Accipiter gentilis", abr: "heja", mon: "333333333333"},
{id: 513, hun: "Barna rétihéja", ltn: "Circus aeruginosus", abr: "barh,brrh", mon: "333333333333"},
{id: 514, hun: "Kékes rétihéja", ltn: "Circus cyaneus", abr: "kerh,kkrh", mon: "333311113333"},
{id: 515, hun: "Amerikai rétihéja", ltn: "Circus hudsonius", abr: "", mon: null},
{id: 516, hun: "Fakó rétihéja", ltn: "Circus macrourus", abr: "farh,fkrh", mon: "111111111111"},
{id: 517, hun: "Hamvas rétihéja", ltn: "Circus pygargus", abr: "harh,hvrh", mon: "112333333211"},
{id: 518, hun: "Vörös kánya", ltn: "Milvus milvus", abr: "vrka,vrkn", mon: "222222222222"},
{id: 519, hun: "Barna kánya", ltn: "Milvus migrans", abr: "brka,brkn", mon: "112222222211"},
{id: 520, hun: "Sárgacsőrű kánya", ltn: "Milvus aegyptius", abr: "", mon: null},
{id: 521, hun: "Lármás rétisas", ltn: "Haliaeetus vocifer", abr: "", mon: null},
{id: 522, hun: "Szalagos rétisas", ltn: "Haliaeetus leucoryphus", abr: "", mon: null},
{id: 523, hun: "Rétisas", ltn: "Haliaeetus albicilla", abr: "rsas,rtsa,rtss", mon: "333333333333"},
{id: 524, hun: "Fehérfejű rétisas", ltn: "Haliaeetus leucocephalus", abr: "", mon: null},
{id: 525, hun: "Gatyás ölyv", ltn: "Buteo lagopus", abr: "goly,gtov", mon: "333211112233"},
{id: 526, hun: "Pusztai ölyv", ltn: "Buteo rufinus", abr: "ptov", mon: "111111111111"},
{id: 527, hun: "Zöld-foki-szigeteki egerészölyv", ltn: "Buteo bannermani", abr: "", mon: null},
{id: 528, hun: "Egerészölyv", ltn: "Buteo buteo", abr: "eger,egov", mon: "333333333333"},
{id: 529, hun: "Vörösfarkú egerészölyv", ltn: "Buteo buteo vulpinus", abr: "vfeov", mon: "111111111111"},
{id: 530, hun: "Gyöngybagoly", ltn: "Tyto alba", abr: "gybg", mon: "333333333333"},
{id: 531, hun: "Gatyáskuvik", ltn: "Aegolius funereus", abr: "gtkv", mon: "111111111111"},
{id: 532, hun: "Kuvik", ltn: "Athene noctua", abr: "kuvi", mon: "333333333333"},
{id: 533, hun: "Karvalybagoly", ltn: "Surnia ulula", abr: "kvbg", mon: "111111111111"},
{id: 534, hun: "Törpekuvik", ltn: "Glaucidium passerinum", abr: "tpkv", mon: "111111111111"},
{id: 535, hun: "Füleskuvik", ltn: "Otus scops", abr: "flkv", mon: "112333332111"},
{id: 536, hun: "Ciprusi füleskuvik", ltn: "Otus cyprius", abr: "", mon: null},
{id: 537, hun: "Sivatagi füleskuvik", ltn: "Otus brucei", abr: "", mon: null},
{id: 538, hun: "Erdei fülesbagoly", ltn: "Asio otus", abr: "erfb", mon: "333333333333"},
{id: 539, hun: "Réti fülesbagoly", ltn: "Asio flammeus", abr: "rtfb", mon: "222222222222"},
{id: 540, hun: "Mocsári fülesbagoly", ltn: "Asio capensis", abr: "", mon: null},
{id: 541, hun: "Hóbagoly", ltn: "Bubo scandiacus", abr: "hobg", mon: "111111111111"},
{id: 542, hun: "Uhu", ltn: "Bubo bubo", abr: "uhu", mon: "222222222222"},
{id: 543, hun: "Sivatagi uhu", ltn: "Bubo ascalaphus", abr: "", mon: null},
{id: 544, hun: "Indiai halászbagoly", ltn: "Ketupa zeylonensis", abr: "", mon: null},
{id: 545, hun: "Macskabagoly", ltn: "Strix aluco", abr: "mcbg", mon: "333333333333"},
{id: 546, hun: "Atlaszi bagoly", ltn: "Strix mauritanica", abr: "", mon: null},
{id: 547, hun: "Sivatagi bagoly", ltn: "Strix hadorami", abr: "", mon: null},
{id: 548, hun: "Uráli bagoly", ltn: "Strix uralensis", abr: "urbg", mon: "222222222222"},
{id: 549, hun: "Szakállas bagoly", ltn: "Strix nebulosa", abr: "", mon: null},
{id: 550, hun: "Kéknyakú egérmadár", ltn: "Urocolius macrourus", abr: "", mon: null},
{id: 551, hun: "Búbosbanka", ltn: "Upupa epops", abr: "buba,bbbk", mon: "113333333211"},
{id: 552, hun: "Bengál szalakóta", ltn: "Coracias benghalensis", abr: "", mon: null},
{id: 553, hun: "Fecskefarkú szalakóta", ltn: "Coracias abyssinicus", abr: "", mon: null},
{id: 554, hun: "Szalakóta", ltn: "Coracias garrulus", abr: "szal", mon: "111333333211"},
{id: 555, hun: "Lilatorkú csörgőmadár", ltn: "Eurystomus glaucurus", abr: "", mon: null},
{id: 556, hun: "Barna halkapó", ltn: "Halcyon smyrnensis", abr: "", mon: null},
{id: 557, hun: "Szürkefejű halkapó", ltn: "Halcyon leucocephala", abr: "", mon: null},
{id: 558, hun: "Jégmadár", ltn: "Alcedo atthis", abr: "jegm,jgmd", mon: "333333333333"},
{id: 559, hun: "Örvös halkapó", ltn: "Megaceryle alcyon", abr: "", mon: null},
{id: 560, hun: "Tarka halkapó", ltn: "Ceryle rudis", abr: "", mon: null},
{id: 561, hun: "Fehértorkú gyurgyalag", ltn: "Merops albicollis", abr: "", mon: null},
{id: 562, hun: "Smaragd gyurgyalag", ltn: "Merops viridissimus", abr: "", mon: null},
{id: 563, hun: "Arab gyurgyalag", ltn: "Merops cyanophrys", abr: "", mon: null},
{id: 564, hun: "Zöld gyurgyalag", ltn: "Merops persicus", abr: "zdgy", mon: "111111111111"},
{id: 565, hun: "Gyurgyalag", ltn: "Merops apiaster", abr: "gyur", mon: "111333333111"},
{id: 566, hun: "Nyaktekercs", ltn: "Jynx torquilla", abr: "nytk", mon: "112333333211"},
{id: 567, hun: "Sárgahasú cukorharkály", ltn: "Sphyrapicus varius", abr: "", mon: null},
{id: 568, hun: "Háromujjú hőcsik", ltn: "Picoides tridactylus", abr: "", mon: null},
{id: 569, hun: "Közép fakopáncs", ltn: "Dendrocoptes medius", abr: "kzfk,koth,kzth", mon: "333333333333"},
{id: 570, hun: "Afrikai szürkeharkály", ltn: "Dendropicos goertae", abr: "", mon: null},
{id: 571, hun: "Kis fakopáncs", ltn: "Dryobates minor", abr: "ksfk,kith,ksth", mon: "333333333333"},
{id: 572, hun: "Balkáni fakopáncs", ltn: "Dendrocopos syriacus", abr: "bkfk,bath,bkth", mon: "333333333333"},
{id: 573, hun: "Nagy fakopáncs", ltn: "Dendrocopos major", abr: "ngfk,nath,ngth", mon: "333333333333"},
{id: 574, hun: "Fehérhátú fakopáncs", ltn: "Dendrocopos leucotos", abr: "fhfk,fhhk", mon: "222222222222"},
{id: 575, hun: "Északi hangyászküllő", ltn: "Colaptes auratus", abr: "", mon: null},
{id: 576, hun: "Fekete harkály", ltn: "Dryocopus martius", abr: "fkha", mon: "333333333333"},
{id: 577, hun: "Zöld küllő", ltn: "Picus viridis", abr: "zdku", mon: "333333333333"},
{id: 578, hun: "Ibériai küllő", ltn: "Picus sharpei", abr: "", mon: null},
{id: 579, hun: "Atlaszi küllő", ltn: "Picus vaillantii", abr: "", mon: null},
{id: 580, hun: "Hamvas küllő", ltn: "Picus canus", abr: "hvku", mon: "333333333333"},
{id: 581, hun: "Fehérkarmú vércse", ltn: "Falco naumanni", abr: "fkve,fkvc", mon: "111111111111"},
{id: 582, hun: "Vörös vércse", ltn: "Falco tinnunculus", abr: "vove,vrve,vrvc", mon: "333333333333"},
{id: 583, hun: "Tarka vércse", ltn: "Falco sparverius", abr: "", mon: null},
{id: 584, hun: "Kék vércse", ltn: "Falco vespertinus", abr: "kkve,kkvc", mon: "111333333211"},
{id: 585, hun: "Amuri vércse", ltn: "Falco amurensis", abr: "amvc", mon: "111111111111"},
{id: 586, hun: "Eleonóra-sólyom", ltn: "Falco eleonorae", abr: "elsm,elso", mon: "111111111111"},
{id: 587, hun: "Hamvas sólyom", ltn: "Falco concolor", abr: "", mon: null},
{id: 588, hun: "Kis sólyom", ltn: "Falco columbarius", abr: "kiso,ksso,kssm", mon: "222211112222"},
{id: 589, hun: "Kabasólyom", ltn: "Falco subbuteo", abr: "kaba,kbso,kbsm", mon: "111333333321"},
{id: 590, hun: "Feldegg-sólyom", ltn: "Falco biarmicus", abr: "", mon: null},
{id: 591, hun: "Kerecsensólyom", ltn: "Falco cherrug", abr: "kere,krso,krsm", mon: "223333222222"},
{id: 592, hun: "Északi sólyom", ltn: "Falco rusticolus", abr: "", mon: null},
{id: 593, hun: "Vándorsólyom", ltn: "Falco peregrinus", abr: "vdso,vdsm", mon: "222222222222"},
{id: 594, hun: "Sivatagi sólyom", ltn: "Falco peregrinus pelegrinoides", abr: "", mon: null},
{id: 595, hun: "Barátpapagáj", ltn: "Myiopsitta monachus", abr: "", mon: null},
{id: 596, hun: "Kucsmás papagáj", ltn: "Aratinga nenday", abr: "", mon: null},
{id: 597, hun: "Gvajakil-papagáj", ltn: "Psittacara erythrogenys", abr: "", mon: null},
{id: 598, hun: "Nagy sándorpapagáj", ltn: "Psittacula eupatria", abr: "", mon: null},
{id: 599, hun: "Örvös papagáj", ltn: "Psittacula krameri", abr: "", mon: null},
{id: 600, hun: "Szürke légykapótirannusz", ltn: "Sayornis phoebe", abr: "", mon: null},
{id: 601, hun: "Keleti pivi", ltn: "Contopus virens", abr: "", mon: null},
{id: 602, hun: "Sárgahasú tirannusz", ltn: "Empidonax flaviventris", abr: "", mon: null},
{id: 603, hun: "Zöldes tirannusz", ltn: "Empidonax virescens", abr: "", mon: null},
{id: 604, hun: "Égertirannusz", ltn: "Empidonax alnorum", abr: "", mon: null},
{id: 605, hun: "Törpetirannusz", ltn: "Empidonax minimus", abr: "", mon: null},
{id: 606, hun: "Nyugati királytirannusz", ltn: "Tyrannus verticalis", abr: "", mon: null},
{id: 607, hun: "Villásfarkú tirannusz", ltn: "Tyrannus savana", abr: "", mon: null},
{id: 608, hun: "Keleti királytirannusz", ltn: "Tyrannus tyrannus", abr: "", mon: null},
{id: 609, hun: "Barátcsagra", ltn: "Tchagra senegalus", abr: "", mon: null},
{id: 610, hun: "Barna gébics", ltn: "Lanius cristatus", abr: "", mon: null},
{id: 611, hun: "Tövisszúró gébics", ltn: "Lanius collurio", abr: "tgeb,tvgb", mon: "111333333321"},
{id: 612, hun: "Pusztai gébics", ltn: "Lanius isabellinus", abr: "", mon: null},
{id: 613, hun: "Turkesztáni gébics", ltn: "Lanius phoenicuroides", abr: "", mon: null},
{id: 614, hun: "Rozsdáshátú gébics", ltn: "Lanius vittatus", abr: "", mon: null},
{id: 615, hun: "Hosszúfarkú gébics", ltn: "Lanius schach", abr: "", mon: null},
{id: 616, hun: "Kis őrgébics", ltn: "Lanius minor", abr: "korg,ksog", mon: "111233333111"},
{id: 617, hun: "Tajgai őrgébics", ltn: "Lanius borealis", abr: "", mon: null},
{id: 618, hun: "Nagy őrgébics", ltn: "Lanius excubitor", abr: "norg,ngog", mon: "333322223333"},
{id: 619, hun: "Ibériai őrgébics", ltn: "Lanius meridionalis", abr: "", mon: null},
{id: 620, hun: "Szalagos gébics", ltn: "Lanius excubitoroides", abr: "", mon: null},
{id: 621, hun: "Vörösfejű gébics", ltn: "Lanius senator", abr: "vfgb", mon: "111111111111"},
{id: 622, hun: "Álarcos gébics", ltn: "Lanius nubicus", abr: "", mon: null},
{id: 623, hun: "Fehérszemű lombgébics", ltn: "Vireo griseus", abr: "", mon: null},
{id: 624, hun: "Sárgatorkú lombgébics", ltn: "Vireo flavifrons", abr: "", mon: null},
{id: 625, hun: "Énekes lombgébics", ltn: "Vireo gilvus", abr: "", mon: null},
{id: 626, hun: "Sárgahasú lombgébics", ltn: "Vireo philadelphicus", abr: "", mon: null},
{id: 627, hun: "Pirosszemű lombgébics", ltn: "Vireo olivaceus", abr: "", mon: null},
{id: 628, hun: "Sárgarigó", ltn: "Oriolus oriolus", abr: "sari,sarg,srrg", mon: "111333333211"},
{id: 629, hun: "Hamvas drongó", ltn: "Dicrurus leucophaeus", abr: "", mon: null},
{id: 630, hun: "Fekete drongó", ltn: "Dicrurus macrocercus", abr: "", mon: null},
{id: 631, hun: "Északi szajkó", ltn: "Perisoreus infaustus", abr: "", mon: null},
{id: 632, hun: "Szajkó", ltn: "Garrulus glandarius", abr: "szaj", mon: "333333333333"},
{id: 633, hun: "Kékszarka", ltn: "Cyanopica cooki", abr: "", mon: null},
{id: 634, hun: "Szarka", ltn: "Pica pica", abr: "szar,szrk", mon: "333333333333"},
{id: 635, hun: "Magreb-szarka", ltn: "Pica mauritanica", abr: "", mon: null},
{id: 636, hun: "Fenyőszajkó", ltn: "Nucifraga caryocatactes", abr: "fnsz", mon: "111111111111"},
{id: 637, hun: "Havasi varjú", ltn: "Pyrrhocorax pyrrhocorax", abr: "hvvj", mon: "111111111111"},
{id: 638, hun: "Havasi csóka", ltn: "Pyrrhocorax graculus", abr: "hvcs", mon: "111111111111"},
{id: 639, hun: "Csóka", ltn: "Coloeus monedula", abr: "csok", mon: "333333333333"},
{id: 640, hun: "Örvös csóka", ltn: "Coloeus dauuricus", abr: "", mon: null},
{id: 641, hun: "Indiai varjú", ltn: "Corvus splendens", abr: "", mon: null},
{id: 642, hun: "Vetési varjú", ltn: "Corvus frugilegus", abr: "vvar,vtvj", mon: "333333333333"},
{id: 643, hun: "Kormos varjú", ltn: "Corvus corone", abr: "kmvj", mon: "222222222222"},
{id: 644, hun: "Dolmányos varjú", ltn: "Corvus cornix", abr: "dvar,dmvj", mon: "333333333333"},
{id: 645, hun: "Pajzsos varjú", ltn: "Corvus albus", abr: "", mon: null},
{id: 646, hun: "Barnanyakú holló", ltn: "Corvus ruficollis", abr: "", mon: null},
{id: 647, hun: "Holló", ltn: "Corvus corax", abr: "holl", mon: "333333333333"},
{id: 648, hun: "Csutakfarkú holló", ltn: "Corvus rhipidurus", abr: "", mon: null},
{id: 649, hun: "Csonttollú", ltn: "Bombycilla garrulus", abr: "cson", mon: "222211111112"},
{id: 650, hun: "Cédruscsonttollú", ltn: "Bombycilla cedrorum", abr: "", mon: null},
{id: 651, hun: "Selyemgébics", ltn: "Hypocolius ampelinus", abr: "", mon: null},
{id: 652, hun: "Fenyvescinege", ltn: "Periparus ater", abr: "fvci,fvcn", mon: "333333333333"},
{id: 653, hun: "Búbos cinege", ltn: "Lophophanes cristatus", abr: "bbci,bbcn", mon: "333333333333"},
{id: 654, hun: "Füstös cinege", ltn: "Poecile lugubris", abr: "", mon: null},
{id: 655, hun: "Lappföldi cinege", ltn: "Poecile cinctus", abr: "", mon: null},
{id: 656, hun: "Barátcinege", ltn: "Poecile palustris", abr: "baci,brci,brcn", mon: "333333333333"},
{id: 657, hun: "Kaszpi cinege", ltn: "Poecile hyrcanus", abr: "", mon: null},
{id: 658, hun: "Kormosfejű cinege", ltn: "Poecile montanus", abr: "kfci,kfcn", mon: "222222222222"},
{id: 659, hun: "Atlaszi cinege", ltn: "Cyanistes teneriffae", abr: "", mon: null},
{id: 660, hun: "Kék cinege", ltn: "Cyanistes caeruleus", abr: "keci,kkci,kkcn", mon: "333333333333"},
{id: 661, hun: "Lazúrcinege", ltn: "Cyanistes cyanus", abr: "", mon: "111111111111"},
{id: 662, hun: "Széncinege", ltn: "Parus major", abr: "szci,szcn", mon: "333333333333"},
{id: 663, hun: "Függőcinege", ltn: "Remiz pendulinus", abr: "fgci,fgcn", mon: "333333333333"},
{id: 664, hun: "Barkóscinege", ltn: "Panurus biarmicus", abr: "bkci,bkcn", mon: "333333333333"},
{id: 665, hun: "Sarlóscsőrű pacsirta", ltn: "Alaemon alaudipes", abr: "", mon: null},
{id: 666, hun: "Vastagcsőrű pacsirta", ltn: "Ramphocoris clotbey", abr: "", mon: null},
{id: 667, hun: "Sivatagi pacsirta", ltn: "Ammomanes deserti", abr: "", mon: null},
{id: 668, hun: "Homoki pacsirta", ltn: "Ammomanes cinctura", abr: "", mon: null},
{id: 669, hun: "Fehérhomlokú verébpacsirta", ltn: "Eremopterix nigriceps", abr: "", mon: null},
{id: 670, hun: "Barnafejű verébpacsirta", ltn: "Eremopterix signatus", abr: "", mon: null},
{id: 671, hun: "Kordofáni bozótpacsirta", ltn: "Mirafra cordofanica", abr: "", mon: null},
{id: 672, hun: "Erdei pacsirta", ltn: "Lullula arborea", abr: "erpa,erpc", mon: "233333333332"},
{id: 673, hun: "Fehérszárnyú pacsirta", ltn: "Alauda leucoptera", abr: "", mon: null},
{id: 674, hun: "Razoi pacsirta", ltn: "Alauda razae", abr: "", mon: null},
{id: 675, hun: "Keleti pacsirta", ltn: "Alauda gulgula", abr: "", mon: null},
{id: 676, hun: "Mezei pacsirta", ltn: "Alauda arvensis", abr: "mepa,mzpa,mzpc", mon: "333333333333"},
{id: 677, hun: "Kövi pacsirta", ltn: "Galerida theklae", abr: "", mon: null},
{id: 678, hun: "Búbospacsirta", ltn: "Galerida cristata", abr: "bupa,bbpa,bbpc", mon: "333333333333"},
{id: 679, hun: "Magreb-pacsirta", ltn: "Galerida macrorhyncha", abr: "", mon: null},
{id: 680, hun: "Havasi fülespacsirta", ltn: "Eremophila alpestris", abr: "hfpa,hfpc", mon: "111111111111"},
{id: 681, hun: "Sivatagi fülespacsirta", ltn: "Eremophila bilopha", abr: "", mon: null},
{id: 682, hun: "Indiai szikipacsirta", ltn: "Calandrella acutirostris", abr: "", mon: null},
{id: 683, hun: "Szikipacsirta", ltn: "Calandrella brachydactyla", abr: "szpa,szpc", mon: "111111111111"},
{id: 684, hun: "Hegyi kalandrapacsirta", ltn: "Melanocorypha bimaculata", abr: "", mon: null},
{id: 685, hun: "Kalandrapacsirta", ltn: "Melanocorypha calandra", abr: "klpa,klpc", mon: "111111111111"},
{id: 686, hun: "Szerecsenpacsirta", ltn: "Melanocorypha yeltoniensis", abr: "", mon: null},
{id: 687, hun: "Vékonycsőrű pacsirta", ltn: "Chersophilus duponti", abr: "", mon: null},
{id: 688, hun: "Nomádpacsirta", ltn: "Eremalauda dunni", abr: "", mon: null},
{id: 689, hun: "Arab nomádpacsirta", ltn: "Eremalauda eremodites", abr: "", mon: null},
{id: 690, hun: "Csíkos szikipacsirta", ltn: "Alaudala rufescens", abr: "", mon: null},
{id: 691, hun: "Turkesztáni szikipacsirta", ltn: "Alaudala heinei", abr: "", mon: null},
{id: 692, hun: "Vörösfülű bülbül", ltn: "Pycnonotus jocosus", abr: "", mon: null},
{id: 693, hun: "Pikkelyes bülbül", ltn: "Pycnonotus cafer", abr: "", mon: null},
{id: 694, hun: "Fehérarcú bülbül", ltn: "Pycnonotus leucotis", abr: "", mon: null},
{id: 695, hun: "Pápaszemes bülbül", ltn: "Pycnonotus xanthopygos", abr: "", mon: null},
{id: 696, hun: "Barna bülbül", ltn: "Pycnonotus barbatus", abr: "", mon: null},
{id: 697, hun: "Barnatorkú partifecske", ltn: "Riparia paludicola", abr: "", mon: null},
{id: 698, hun: "Szürketorkú partifecske", ltn: "Riparia chinensis", abr: "", mon: null},
{id: 699, hun: "Partifecske", ltn: "Riparia riparia", abr: "pafe,ptfe,ptfk", mon: "112333333211"},
{id: 700, hun: "Halvány partifecske", ltn: "Riparia diluta", abr: "", mon: null},
{id: 701, hun: "Szalagos partifecske", ltn: "Riparia cincta", abr: "", mon: null},
{id: 702, hun: "Odúfecske", ltn: "Tachycineta bicolor", abr: "", mon: null},
{id: 703, hun: "Bíborfecske", ltn: "Progne subis", abr: "", mon: null},
{id: 704, hun: "Füsti fecske", ltn: "Hirundo rustica", abr: "fufe,ftfe,ftfk", mon: "113333333311"},
{id: 705, hun: "Nílusi fecske", ltn: "Hirundo aethiopica", abr: "", mon: null},
{id: 706, hun: "Szirtifecske", ltn: "Ptyonoprogne rupestris", abr: "szfe,szfk", mon: "111111111111"},
{id: 707, hun: "Sivatagi szirtifecske", ltn: "Ptyonoprogne obsoleta", abr: "", mon: null},
{id: 708, hun: "Molnárfecske", ltn: "Delichon urbicum", abr: "mofe,mnfe,mnfc", mon: "113333333311"},
{id: 709, hun: "Ázsiai molnárfecske", ltn: "Delichon dasypus", abr: "", mon: null},
{id: 710, hun: "Vörhenyes fecske", ltn: "Cecropis daurica", abr: "vhfe,vhfk", mon: "111111111111"},
{id: 711, hun: "Preuss-sziklafecske", ltn: "Petrochelidon preussi", abr: "", mon: null},
{id: 712, hun: "Csíkostorkú sziklafecske", ltn: "Petrochelidon fluvicola", abr: "", mon: null},
{id: 713, hun: "Sziklafecske", ltn: "Petrochelidon pyrrhonota", abr: "", mon: null},
{id: 714, hun: "Berki poszáta", ltn: "Cettia cetti", abr: "bkpo,bkps", mon: "111111111111"},
{id: 715, hun: "Fürge prínia", ltn: "Scotocerca inquieta", abr: "", mon: null},
{id: 716, hun: "Őszapó", ltn: "Aegithalos caudatus", abr: "osza", mon: "333333333333"},
{id: 717, hun: "Sisegő füzike", ltn: "Phylloscopus sibilatrix", abr: "sifu,ssfz", mon: "112333333211"},
{id: 718, hun: "Bonelli-füzike", ltn: "Phylloscopus bonelli", abr: "bnfz", mon: "111111111111"},
{id: 719, hun: "Balkáni füzike", ltn: "Phylloscopus orientalis", abr: "", mon: null},
{id: 720, hun: "Himalájai füzike", ltn: "Phylloscopus humei", abr: "hmfz", mon: "111111111111"},
{id: 721, hun: "Vándorfüzike", ltn: "Phylloscopus inornatus", abr: "vdfz", mon: "111111111111"},
{id: 722, hun: "Királyfüzike", ltn: "Phylloscopus proregulus", abr: "krfz", mon: "111111111111"},
{id: 723, hun: "Vastagcsőrű füzike", ltn: "Phylloscopus schwarzi", abr: "vcfz", mon: "111111111111"},
{id: 724, hun: "Kénsárga füzike", ltn: "Phylloscopus griseolus", abr: "", mon: null},
{id: 725, hun: "Barna füzike", ltn: "Phylloscopus fuscatus", abr: "brfz", mon: "111111111111"},
{id: 726, hun: "Perzsa füzike", ltn: "Phylloscopus neglectus", abr: "", mon: null},
{id: 727, hun: "Fitiszfüzike", ltn: "Phylloscopus trochilus", abr: "ftfz", mon: "113333333321"},
{id: 728, hun: "Hegyi füzike", ltn: "Phylloscopus sindianus", abr: "", mon: null},
{id: 729, hun: "Kanári füzike", ltn: "Phylloscopus canariensis", abr: "", mon: null},
{id: 730, hun: "Csilpcsalpfüzike", ltn: "Phylloscopus collybita", abr: "csfu,csfz", mon: "223333333332"},
{id: 731, hun: "Szibériai csilpcsalpfüzike", ltn: "Phylloscopus collybita tristis", abr: "", mon: "111111111111"},
{id: 732, hun: "Ibériai füzike", ltn: "Phylloscopus ibericus", abr: "", mon: null},
{id: 733, hun: "Koronás füzike", ltn: "Phylloscopus coronatus", abr: "", mon: null},
{id: 734, hun: "Kaukázusi füzike", ltn: "Phylloscopus nitidus", abr: "", mon: null},
{id: 735, hun: "Szalagos füzike", ltn: "Phylloscopus plumbeitarsus", abr: "", mon: null},
{id: 736, hun: "Sárga füzike", ltn: "Phylloscopus trochiloides", abr: "", mon: null},
{id: 737, hun: "Amuri füzike", ltn: "Phylloscopus tenellipes", abr: "", mon: null},
{id: 738, hun: "Kamcsatkai füzike", ltn: "Phylloscopus examinandus", abr: "", mon: null},
{id: 739, hun: "Északi füzike", ltn: "Phylloscopus borealis", abr: "", mon: null},
{id: 740, hun: "Eufráteszi nádirigó", ltn: "Acrocephalus griseldis", abr: "", mon: null},
{id: 741, hun: "Zöld-foki-szigeteki nádiposzáta", ltn: "Acrocephalus brevipennis", abr: "", mon: null},
{id: 742, hun: "Nádirigó", ltn: "Acrocephalus arundinaceus", abr: "ndrg", mon: "112333333311"},
{id: 743, hun: "Keleti nádirigó", ltn: "Acrocephalus orientalis", abr: "", mon: null},
{id: 744, hun: "Hosszúcsőrű nádirigó", ltn: "Acrocephalus stentoreus", abr: "", mon: null},
{id: 745, hun: "Fülemülesitke", ltn: "Acrocephalus melanopogon", abr: "flsk", mon: "123333333331"},
{id: 746, hun: "Csíkosfejű nádiposzáta", ltn: "Acrocephalus paludicola", abr: "cfnp", mon: "111111111111"},
{id: 747, hun: "Foltos nádiposzáta", ltn: "Acrocephalus schoenobaenus", abr: "fonp,ftnp", mon: "113333333311"},
{id: 748, hun: "Rozsdás nádiposzáta", ltn: "Acrocephalus agricola", abr: "rdnp", mon: "111111111111"},
{id: 749, hun: "Berki nádiposzáta", ltn: "Acrocephalus dumetorum", abr: "bknp", mon: "111111111111"},
{id: 750, hun: "Cserregő nádiposzáta", ltn: "Acrocephalus scirpaceus", abr: "csnp", mon: "113333333311"},
{id: 751, hun: "Afrikai nádiposzáta", ltn: "Acrocephalus baeticatus", abr: "", mon: null},
{id: 752, hun: "Énekes nádiposzáta", ltn: "Acrocephalus palustris", abr: "ennp", mon: "111333333211"},
{id: 753, hun: "Vastagcsőrű nádirigó", ltn: "Arundinax aedon", abr: "", mon: null},
{id: 754, hun: "Kis geze", ltn: "Iduna caligata", abr: "ksge,ksgz", mon: "000000000000"},
{id: 755, hun: "Perzsa geze", ltn: "Iduna rama", abr: "", mon: null},
{id: 756, hun: "Halvány geze", ltn: "Iduna pallida", abr: "hvge,hvgz", mon: "111222221111"},
{id: 757, hun: "Spanyol geze", ltn: "Iduna opaca", abr: "", mon: null},
{id: 758, hun: "Bozótgeze", ltn: "Hippolais languida", abr: "", mon: null},
{id: 759, hun: "Olívgeze", ltn: "Hippolais olivetorum", abr: "", mon: null},
{id: 760, hun: "Déli geze", ltn: "Hippolais polyglotta", abr: "dlge,dlgz", mon: "111111111111"},
{id: 761, hun: "Kerti geze", ltn: "Hippolais icterina", abr: "ktge,ktgz", mon: "111233333211"},
{id: 762, hun: "Dalos tücsökmadár", ltn: "Helopsaltes fasciolatus", abr: "", mon: null},
{id: 763, hun: "Csíkos tücsökmadár", ltn: "Helopsaltes certhiola", abr: "", mon: null},
{id: 764, hun: "Foltos tücsökmadár", ltn: "Locustella lanceolata", abr: "", mon: null},
{id: 765, hun: "Berki tücsökmadár", ltn: "Locustella fluviatilis", abr: "betm,bktm", mon: "111333333211"},
{id: 766, hun: "Nádi tücsökmadár", ltn: "Locustella luscinioides", abr: "ndtm", mon: "113333333211"},
{id: 767, hun: "Réti tücsökmadár", ltn: "Locustella naevia", abr: "rttm", mon: "111333333211"},
{id: 768, hun: "Szuharbújó", ltn: "Cisticola juncidis", abr: "szbj", mon: "111111111111"},
{id: 769, hun: "Karcsú prínia", ltn: "Prinia gracilis", abr: "", mon: null},
{id: 770, hun: "Csinos prínia", ltn: "Prinia lepida", abr: "", mon: null},
{id: 771, hun: "Tücsökprínia", ltn: "Spiloptila clamans", abr: "", mon: null},
{id: 772, hun: "Barátposzáta", ltn: "Sylvia atricapilla", abr: "brpo", mon: "333333333333"},
{id: 773, hun: "Kerti poszáta", ltn: "Sylvia borin", abr: "ktpo", mon: "111233333311"},
{id: 774, hun: "Karvalyposzáta", ltn: "Curruca nisoria", abr: "kvpo", mon: "111333333211"},
{id: 775, hun: "Kis poszáta", ltn: "Curruca curruca", abr: "kspo", mon: "113333333321"},
{id: 776, hun: "Hume-poszáta", ltn: "Curruca althaea", abr: "", mon: null},
{id: 777, hun: "Arab poszáta", ltn: "Curruca leucomelaena", abr: "", mon: null},
{id: 778, hun: "Dalos poszáta", ltn: "Curruca hortensis", abr: "", mon: null},
{id: 779, hun: "Balkáni poszáta", ltn: "Curruca crassirostris", abr: "", mon: null},
{id: 780, hun: "Szaharai poszáta", ltn: "Curruca deserti", abr: "", mon: null},
{id: 781, hun: "Sivatagi poszáta", ltn: "Curruca nana", abr: "", mon: null},
{id: 782, hun: "Atlaszi poszáta", ltn: "Curruca deserticola", abr: "", mon: null},
{id: 783, hun: "Tamariszkuszposzáta", ltn: "Curruca mystacea", abr: "", mon: null},
{id: 784, hun: "Feketetorkú poszáta", ltn: "Curruca ruppeli", abr: "", mon: null},
{id: 785, hun: "Ciprusi poszáta", ltn: "Curruca melanothorax", abr: "", mon: null},
{id: 786, hun: "Kucsmás poszáta", ltn: "Curruca melanocephala", abr: "kmpo", mon: "111111111111"},
{id: 787, hun: "Ibériai poszáta", ltn: "Curruca iberiae", abr: "", mon: null},
{id: 788, hun: "Moltoni-poszáta", ltn: "Curruca subalpina", abr: "", mon: null},
{id: 789, hun: "Bajszos poszáta", ltn: "Curruca cantillans", abr: "bspo", mon: "111111111111"},
{id: 790, hun: "Mezei poszáta", ltn: "Curruca communis", abr: "mzpo", mon: "112333333211"},
{id: 791, hun: "Törpeposzáta", ltn: "Curruca conspicillata", abr: "", mon: null},
{id: 792, hun: "Szardíniai poszáta", ltn: "Curruca sarda", abr: "", mon: null},
{id: 793, hun: "Bujkáló poszáta", ltn: "Curruca undata", abr: "", mon: null},
{id: 794, hun: "Baleár-szigeteki poszáta", ltn: "Curruca balearica", abr: "", mon: null},
{id: 795, hun: "Barnatorkú papagájcinege", ltn: "Sinosuthora webbiana", abr: "", mon: null},
{id: 796, hun: "Szürketorkú papagájcinege", ltn: "Sinosuthora alphonsiana", abr: "", mon: null},
{id: 797, hun: "Piroscsőrű napmadár", ltn: "Leiothrix lutea", abr: "", mon: null},
{id: 798, hun: "Iraki rigótimália", ltn: "Argya altirostris", abr: "", mon: null},
{id: 799, hun: "Afgán rigótimália", ltn: "Argya huttoni", abr: "", mon: null},
{id: 800, hun: "Vörhenyes rigótimália", ltn: "Argya fulva", abr: "", mon: null},
{id: 801, hun: "Arab rigótimália", ltn: "Argya squamiceps", abr: "", mon: null},
{id: 802, hun: "Tüzesfejű királyka", ltn: "Regulus ignicapilla", abr: "tfkr,tkir", mon: "222222222222"},
{id: 803, hun: "Sárgafejű királyka", ltn: "Regulus regulus", abr: "sfkr,skir", mon: "333333333333"},
{id: 804, hun: "Madeirai királyka", ltn: "Regulus madeirensis", abr: "", mon: null},
{id: 805, hun: "Rubinfejű királyka", ltn: "Regulus calendula", abr: "", mon: null},
{id: 806, hun: "Ökörszem", ltn: "Troglodytes troglodytes", abr: "okor", mon: "333333333333"},
{id: 807, hun: "Atlaszi csuszka", ltn: "Sitta ledanti", abr: "", mon: null},
{id: 808, hun: "Török csuszka", ltn: "Sitta krueperi", abr: "", mon: null},
{id: 809, hun: "Kanadai csuszka", ltn: "Sitta canadensis", abr: "", mon: null},
{id: 810, hun: "Korzikai csuszka", ltn: "Sitta whiteheadi", abr: "", mon: null},
{id: 811, hun: "Kövi csuszka", ltn: "Sitta neumayer", abr: "", mon: null},
{id: 812, hun: "Szirti csuszka", ltn: "Sitta tephronota", abr: "", mon: null},
{id: 813, hun: "Csuszka", ltn: "Sitta europaea", abr: "csus", mon: "333333333333"},
{id: 814, hun: "Hajnalmadár", ltn: "Tichodroma muraria", abr: "hajn", mon: "111111111111"},
{id: 815, hun: "Hegyi fakusz", ltn: "Certhia familiaris", abr: "hfak,hgfk", mon: "333333333333"},
{id: 816, hun: "Rövidkarmú fakusz", ltn: "Certhia brachydactyla", abr: "rfak,rkfk", mon: "333333333333"},
{id: 817, hun: "Macskamadár", ltn: "Dumetella carolinensis", abr: "", mon: null},
{id: 818, hun: "Énekes gezerigó", ltn: "Mimus polyglottos", abr: "", mon: null},
{id: 819, hun: "Vörhenyes gezerigó", ltn: "Toxostoma rufum", abr: "", mon: null},
{id: 820, hun: "Bóbitás mejnó", ltn: "Acridotheres cristatellus", abr: "", mon: null},
{id: 821, hun: "Hindu mejnó", ltn: "Acridotheres ginginianus", abr: "", mon: null},
{id: 822, hun: "Pásztormejnó", ltn: "Acridotheres tristis", abr: "", mon: null},
{id: 823, hun: "Lazacszínű seregély", ltn: "Acridotheres burmannicus", abr: "", mon: null},
{id: 824, hun: "Bíborhátú seregély", ltn: "Agropsar sturninus", abr: "", mon: null},
{id: 825, hun: "Pásztormadár", ltn: "Pastor roseus", abr: "ptmd", mon: "111111111111"},
{id: 826, hun: "Seregély", ltn: "Sturnus vulgaris", abr: "sere", mon: "333333333333"},
{id: 827, hun: "Egyszínű seregély", ltn: "Sturnus unicolor", abr: "", mon: null},
{id: 828, hun: "Fuvolázó fényseregély", ltn: "Onychognathus tristramii", abr: "", mon: null},
{id: 829, hun: "Szibériai földirigó", ltn: "Geokichla sibirica", abr: "", mon: null},
{id: 830, hun: "Aranyos földirigó", ltn: "Zoothera aurea", abr: "", mon: null},
{id: 831, hun: "Tarka földirigó", ltn: "Ixoreus naevius", abr: "", mon: null},
{id: 832, hun: "Vörhenyes fülemülerigó", ltn: "Catharus fuscescens", abr: "", mon: null},
{id: 833, hun: "Szürkearcú fülemülerigó", ltn: "Catharus minimus", abr: "", mon: null},
{id: 834, hun: "Flótázó fülemülerigó", ltn: "Catharus ustulatus", abr: "", mon: null},
{id: 835, hun: "Pettyes fülemülerigó", ltn: "Catharus guttatus", abr: "", mon: null},
{id: 836, hun: "Erdei fülemülerigó", ltn: "Hylocichla mustelina", abr: "", mon: null},
{id: 837, hun: "Szürke rigó", ltn: "Turdus unicolor", abr: "", mon: null},
{id: 838, hun: "Örvös rigó", ltn: "Turdus torquatus", abr: "orrg", mon: "111111111111"},
{id: 839, hun: "Fekete rigó", ltn: "Turdus merula", abr: "feri,fkri,fkrg", mon: "333333333333"},
{id: 840, hun: "Halvány rigó", ltn: "Turdus obscurus", abr: "", mon: null},
{id: 841, hun: "Feketetorkú rigó", ltn: "Turdus atrogularis", abr: "ftrg", mon: "000000000000"},
{id: 842, hun: "Rőttorkú rigó", ltn: "Turdus ruficollis", abr: "", mon: null},
{id: 843, hun: "Naumann-rigó", ltn: "Turdus naumanni", abr: "nmrg", mon: "111111111111"},
{id: 844, hun: "Rőtszárnyú rigó", ltn: "Turdus eunomus", abr: "", mon: null},
{id: 845, hun: "Fenyőrigó", ltn: "Turdus pilaris", abr: "fnrg", mon: "333333333333"},
{id: 846, hun: "Szőlőrigó", ltn: "Turdus iliacus", abr: "szri,szrg", mon: "333311113333"},
{id: 847, hun: "Énekes rigó", ltn: "Turdus philomelos", abr: "enrg,enri", mon: "333333333333"},
{id: 848, hun: "Léprigó", ltn: "Turdus viscivorus", abr: "lprg,leri", mon: "333333333333"},
{id: 849, hun: "Vándorrigó", ltn: "Turdus migratorius", abr: "", mon: null},
{id: 850, hun: "Fekete tüskebujkáló", ltn: "Cercotrichas podobe", abr: "", mon: null},
{id: 851, hun: "Tüskebujkáló", ltn: "Cercotrichas galactotes", abr: "", mon: null},
{id: 852, hun: "Szürke légykapó", ltn: "Muscicapa striata", abr: "szlk", mon: "111333333311"},
{id: 853, hun: "Mediterrán légykapó", ltn: "Muscicapa tyrrhenica", abr: "", mon: null},
{id: 854, hun: "Füstös légykapó", ltn: "Muscicapa sibirica", abr: "", mon: null},
{id: 855, hun: "Barna légykapó", ltn: "Muscicapa dauurica", abr: "", mon: null},
{id: 856, hun: "Vörösbegy", ltn: "Erithacus rubecula", abr: "vorb", mon: "333333333333"},
{id: 857, hun: "Kék fülemüle", ltn: "Larvivora cyane", abr: "", mon: null},
{id: 858, hun: "Rőtfarkú fülemüle", ltn: "Larvivora sibilans", abr: "", mon: null},
{id: 859, hun: "Kékbegy", ltn: "Luscinia svecica", abr: "kkbg", mon: "113333333211"},
{id: 860, hun: "Vöröscsillagos kékbegy", ltn: "Luscinia svecica svecica", abr: "", mon: "000000000000"},
{id: 861, hun: "Nagy fülemüle", ltn: "Luscinia luscinia", abr: "ngfu,ngfl", mon: "111111111111"},
{id: 862, hun: "Fülemüle", ltn: "Luscinia megarhynchos", abr: "fule", mon: "112333333211"},
{id: 863, hun: "Fehértorkú fülemüle", ltn: "Irania gutturalis", abr: "", mon: null},
{id: 864, hun: "Rubinbegy", ltn: "Calliope calliope", abr: "", mon: null},
{id: 865, hun: "Kékfarkú", ltn: "Tarsiger cyanurus", abr: "kkfk", mon: "111111111111"},
{id: 866, hun: "Fenyveslégykapó", ltn: "Ficedula mugimaki", abr: "", mon: null},
{id: 867, hun: "Szibériai légykapó", ltn: "Ficedula albicilla", abr: "", mon: null},
{id: 868, hun: "Kis légykapó", ltn: "Ficedula parva", abr: "kslk", mon: "111222222111"},
{id: 869, hun: "Félörvös légykapó", ltn: "Ficedula semitorquata", abr: "", mon: null},
{id: 870, hun: "Kormos légykapó", ltn: "Ficedula hypoleuca", abr: "kmlk", mon: "112332233211"},
{id: 871, hun: "Örvös légykapó", ltn: "Ficedula albicollis", abr: "orlk", mon: "112333333211"},
{id: 872, hun: "Atlaszi légykapó", ltn: "Ficedula speculigera", abr: "", mon: null},
{id: 873, hun: "Vöröshátú rozsdafarkú", ltn: "Phoenicurus erythronotus", abr: "", mon: null},
{id: 874, hun: "Házi rozsdafarkú", ltn: "Phoenicurus ochruros", abr: "hrof,hzrf", mon: "333333333333"},
{id: 875, hun: "Kerti rozsdafarkú", ltn: "Phoenicurus phoenicurus", abr: "krof,ktrf", mon: "112333333311"},
{id: 876, hun: "Tükrös rozsdafarkú", ltn: "Phoenicurus auroreus", abr: "", mon: null},
{id: 877, hun: "Gyémántrozsdafarkú", ltn: "Phoenicurus moussieri", abr: "", mon: null},
{id: 878, hun: "Hegyi rozsdafarkú", ltn: "Phoenicurus erythrogastrus", abr: "", mon: null},
{id: 879, hun: "Kövirigó", ltn: "Monticola saxatilis", abr: "kvrg", mon: "111111111111"},
{id: 880, hun: "Kék kövirigó", ltn: "Monticola solitarius", abr: "kkkr", mon: "111111111111"},
{id: 881, hun: "Rozsdás csuk", ltn: "Saxicola rubetra", abr: "rcsu,rdcs", mon: "113333333311"},
{id: 882, hun: "Kanári-szigeteki csuk", ltn: "Saxicola dacotiae", abr: "", mon: null},
{id: 883, hun: "Cigánycsuk", ltn: "Saxicola rubicola", abr: "ccsu,cgcs", mon: "233333333332"},
{id: 884, hun: "Keleti cigánycsuk", ltn: "Saxicola maurus", abr: "", mon: null},
{id: 885, hun: "Stejneger-csuk", ltn: "Saxicola stejnegeri", abr: "", mon: null},
{id: 886, hun: "Gyászos csuk", ltn: "Saxicola caprata", abr: "", mon: null},
{id: 887, hun: "Száheli hangyászcsuk", ltn: "Myrmecocichla aethiops", abr: "", mon: null},
{id: 888, hun: "Hantmadár", ltn: "Oenanthe oenanthe", abr: "hant,htmd", mon: "113333333211"},
{id: 889, hun: "Atlaszi hantmadár", ltn: "Oenanthe seebohmi", abr: "", mon: null},
{id: 890, hun: "Pusztai hantmadár", ltn: "Oenanthe isabellina", abr: "pthm", mon: "111111111111"},
{id: 891, hun: "Csuklyás hantmadár", ltn: "Oenanthe monacha", abr: "", mon: null},
{id: 892, hun: "Sivatagi hantmadár", ltn: "Oenanthe deserti", abr: "svhm", mon: "111111111111"},
{id: 893, hun: "Ibériai hantmadár", ltn: "Oenanthe hispanica", abr: "ibhm", mon: "111111111111"},
{id: 894, hun: "Déli hantmadár", ltn: "Oenanthe melanoleuca", abr: "dlhm", mon: "111111111111"},
{id: 895, hun: "Ciprusi hantmadár", ltn: "Oenanthe cypriaca", abr: "", mon: null},
{id: 896, hun: "Apácahantmadár", ltn: "Oenanthe pleschanka", abr: "aphm", mon: "111111111111"},
{id: 897, hun: "Rozsdás hantmadár", ltn: "Oenanthe moesta", abr: "", mon: null},
{id: 898, hun: "Koromfarkú csuk", ltn: "Oenanthe melanura", abr: "", mon: null},
{id: 899, hun: "Perzsa hantmadár", ltn: "Oenanthe picata", abr: "", mon: null},
{id: 900, hun: "Kormos hantmadár", ltn: "Oenanthe leucura", abr: "", mon: null},
{id: 901, hun: "Koronás hantmadár", ltn: "Oenanthe leucopyga", abr: "", mon: null},
{id: 902, hun: "Feketefejű hantmadár", ltn: "Oenanthe albonigra", abr: "", mon: null},
{id: 903, hun: "Türk hantmadár", ltn: "Oenanthe finschii", abr: "", mon: null},
{id: 904, hun: "Magrebi hantmadár", ltn: "Oenanthe halophila", abr: "", mon: null},
{id: 905, hun: "Gyászos hantmadár", ltn: "Oenanthe lugens", abr: "", mon: null},
{id: 906, hun: "Bazalthantmadár", ltn: "Oenanthe warriae", abr: "", mon: null},
{id: 907, hun: "Kurd hantmadár", ltn: "Oenanthe xanthoprymna", abr: "", mon: null},
{id: 908, hun: "Vörösfarkú hantmadár", ltn: "Oenanthe chrysopygia", abr: "", mon: null},
{id: 909, hun: "Vízirigó", ltn: "Cinclus cinclus", abr: "vzrg", mon: "112222222111"},
{id: 910, hun: "Törpenektármadár", ltn: "Hedydipna platura", abr: "", mon: null},
{id: 911, hun: "Nílusi nektármadár", ltn: "Hedydipna metallica", abr: "", mon: null},
{id: 912, hun: "Jerikói nektármadár", ltn: "Cinnyris osea", abr: "", mon: null},
{id: 913, hun: "Bíbor nektármadár", ltn: "Cinnyris asiaticus", abr: "", mon: null},
{id: 914, hun: "Házi veréb", ltn: "Passer domesticus", abr: "hver,hzvr,hzvb", mon: "333333333333"},
{id: 915, hun: "Olasz veréb", ltn: "Passer italiae", abr: "olvr,olvb", mon: "000000000000"},
{id: 916, hun: "Berki veréb", ltn: "Passer hispaniolensis", abr: "bkvr,bkvb", mon: "111111111111"},
{id: 917, hun: "Tamariszkuszveréb", ltn: "Passer moabiticus", abr: "", mon: null},
{id: 918, hun: "Zöld-foki-szigeteki veréb", ltn: "Passer iagoensis", abr: "", mon: null},
{id: 919, hun: "Sivatagi veréb", ltn: "Passer simplex", abr: "", mon: null},
{id: 920, hun: "Mezei veréb", ltn: "Passer montanus", abr: "mver,mzvr,mzvb", mon: "333333333333"},
{id: 921, hun: "Barnahátú aranyveréb", ltn: "Passer luteus", abr: "", mon: null},
{id: 922, hun: "Halvány köviveréb", ltn: "Carpospiza brachydactyla", abr: "", mon: null},
{id: 923, hun: "Köviveréb", ltn: "Petronia petronia", abr: "", mon: null},
{id: 924, hun: "Barnavállú köviveréb", ltn: "Gymnoris xanthocollis", abr: "", mon: null},
{id: 925, hun: "Havasipinty", ltn: "Montifringilla nivalis", abr: "fvpn", mon: "111111111111"},
{id: 926, hun: "Rüppell-szövőmadár", ltn: "Ploceus galbula", abr: "", mon: null},
{id: 927, hun: "Málinkó-szövőmadár", ltn: "Ploceus cucullatus", abr: "", mon: null},
{id: 928, hun: "Feketefejű szövőmadár", ltn: "Ploceus melanocephalus", abr: "", mon: null},
{id: 929, hun: "Csíkos szövőmadár", ltn: "Ploceus manyar", abr: "", mon: null},
{id: 930, hun: "Sárgafejű szövőpinty", ltn: "Euplectes afer", abr: "", mon: null},
{id: 931, hun: "Afrikai ezüstcsőrűpinty", ltn: "Euodice cantans", abr: "", mon: null},
{id: 932, hun: "Indiai ezüstcsőrűpinty", ltn: "Euodice malabarica", abr: "", mon: null},
{id: 933, hun: "Pikkelyes múnia", ltn: "Lonchura punctulata", abr: "", mon: null},
{id: 934, hun: "Feketefejű szarkapinty", ltn: "Lonchura malacca", abr: "", mon: null},
{id: 935, hun: "Narancsarcú asztrild", ltn: "Estrilda melpoda", abr: "", mon: null},
{id: 936, hun: "Asztrild", ltn: "Estrilda astrild", abr: "", mon: null},
{id: 937, hun: "Korallcsőrű asztrild", ltn: "Estrilda troglodytes", abr: "", mon: null},
{id: 938, hun: "Tigrispinty", ltn: "Amandava amandava", abr: "", mon: null},
{id: 939, hun: "Vöröscsőrű tűzpinty", ltn: "Lagonosticta senegala", abr: "", mon: null},
{id: 940, hun: "Nyílfarkú özvegypinty", ltn: "Vidua macroura", abr: "", mon: null},
{id: 941, hun: "Havasi szürkebegy", ltn: "Prunella collaris", abr: "", mon: "111111111111"},
{id: 942, hun: "Szibériai szürkebegy", ltn: "Prunella montanella", abr: "", mon: "000000000000"},
{id: 943, hun: "Örmény szürkebegy", ltn: "Prunella ocularis", abr: "", mon: null},
{id: 944, hun: "Feketetorkú szürkebegy", ltn: "Prunella atrogularis", abr: "", mon: "111111111111"},
{id: 945, hun: "Erdei szürkebegy", ltn: "Prunella modularis", abr: "eszb,ersb", mon: "333333333333"},
{id: 946, hun: "Szalagos billegető", ltn: "Dendronanthus indicus", abr: "", mon: null},
{id: 947, hun: "Sárga billegető", ltn: "Motacilla flava", abr: "sbil,sgbl", mon: "113333333311"},
{id: 948, hun: "Északi billegető", ltn: "Motacilla flava thunbergi", abr: "esbl", mon: "112222222111"},
{id: 949, hun: "Kucsmás billegető", ltn: "Motacilla flava feldegg", abr: "kmbl", mon: "112222222211"},
{id: 950, hun: "Keleti billegető", ltn: "Motacilla tschutschensis", abr: "", mon: null},
{id: 951, hun: "Citrombillegető", ltn: "Motacilla citreola", abr: "ctbl", mon: "111111111111"},
{id: 952, hun: "Hegyi billegető", ltn: "Motacilla cinerea", abr: "hbil,hgbl", mon: "333333333333"},
{id: 953, hun: "Barázdabillegető", ltn: "Motacilla alba", abr: "bbil,brbl", mon: "333333333333"},
{id: 954, hun: "Angliai barázdabillegető", ltn: "Motacilla alba yarrellii", abr: "", mon: "000000000000"},
{id: 955, hun: "Özvegybillegető", ltn: "Motacilla aguimp", abr: "", mon: null},
{id: 956, hun: "Sarkantyús pityer", ltn: "Anthus richardi", abr: "skpt", mon: "111111111111"},
{id: 957, hun: "Indiai pityer", ltn: "Anthus rufulus", abr: "", mon: null},
{id: 958, hun: "Mongol pityer", ltn: "Anthus godlewskii", abr: "", mon: null},
{id: 959, hun: "Parlagi pityer", ltn: "Anthus campestris", abr: "plpt", mon: "112333333211"},
{id: 960, hun: "Hosszúcsőrű pityer", ltn: "Anthus similis", abr: "", mon: null},
{id: 961, hun: "Réti pityer", ltn: "Anthus pratensis", abr: "rtpt", mon: "333331123333"},
{id: 962, hun: "Erdei pityer", ltn: "Anthus trivialis", abr: "erpt", mon: "113333333321"},
{id: 963, hun: "Olívhátú pityer", ltn: "Anthus hodgsoni", abr: "", mon: null},
{id: 964, hun: "Tundrapityer", ltn: "Anthus gustavi", abr: "", mon: null},
{id: 965, hun: "Rozsdástorkú pityer", ltn: "Anthus cervinus", abr: "rdpt", mon: "112332233311"},
{id: 966, hun: "Vörhenyes pityer", ltn: "Anthus rubescens", abr: "", mon: null},
{id: 967, hun: "Havasi pityer", ltn: "Anthus spinoletta", abr: "hvpt", mon: "333311113333"},
{id: 968, hun: "Parti pityer", ltn: "Anthus petrosus", abr: "ptpt", mon: "111111111111"},
{id: 969, hun: "Kanári-szigeteki pityer", ltn: "Anthus berthelotii", abr: "", mon: null},
{id: 970, hun: "Erdei pinty", ltn: "Fringilla coelebs", abr: "epin,erpn", mon: "333333333333"},
{id: 971, hun: "Kékpinty", ltn: "Fringilla teydea", abr: "", mon: null},
{id: 972, hun: "Halvány kékpinty", ltn: "Fringilla polatzeki", abr: "", mon: null},
{id: 973, hun: "Fenyőpinty", ltn: "Fringilla montifringilla", abr: "fpin,fnpn", mon: "333321112333"},
{id: 974, hun: "Koronás meggyvágó", ltn: "Hesperiphona vespertina", abr: "", mon: null},
{id: 975, hun: "Meggyvágó", ltn: "Coccothraustes coccothraustes", abr: "megg", mon: "333333333333"},
{id: 976, hun: "Nagy pirók", ltn: "Pinicola enucleator", abr: "ngpr", mon: "111111111111"},
{id: 977, hun: "Süvöltő", ltn: "Pyrrhula pyrrhula", abr: "suvo", mon: "333311113333"},
{id: 978, hun: "Azori süvöltő", ltn: "Pyrrhula murina", abr: "", mon: null},
{id: 979, hun: "Ázsiai rózsásszárnyúpinty", ltn: "Rhodopechys sanguineus", abr: "", mon: null},
{id: 980, hun: "Atlaszi rózsásszárnyúpinty", ltn: "Rhodopechys alienus", abr: "", mon: null},
{id: 981, hun: "Trombitás sivatagipinty", ltn: "Bucanetes githagineus", abr: "", mon: "111111111111"},
{id: 982, hun: "Mongol sivatagipinty", ltn: "Bucanetes mongolicus", abr: "", mon: null},
{id: 983, hun: "Karmazsinpirók", ltn: "Carpodacus erythrinus", abr: "kmpr", mon: "111111111111"},
{id: 984, hun: "Kaukázusi pirók", ltn: "Carpodacus rubicilla", abr: "", mon: null},
{id: 985, hun: "Sivatagi pirók", ltn: "Carpodacus synoicus", abr: "", mon: null},
{id: 986, hun: "Hosszúfarkú pirók", ltn: "Carpodacus sibiricus", abr: "", mon: null},
{id: 987, hun: "Rózsás pirók", ltn: "Carpodacus roseus", abr: "rzpr", mon: "111111111111"},
{id: 988, hun: "Zöldike", ltn: "Chloris chloris", abr: "zold", mon: "333333333333"},
{id: 989, hun: "Feketecsőrű sivatagipinty", ltn: "Rhodospiza obsoleta", abr: "", mon: null},
{id: 990, hun: "Sárgacsőrű kenderike", ltn: "Linaria flavirostris", abr: "sckd", mon: "111111111111"},
{id: 991, hun: "Kenderike", ltn: "Linaria cannabina", abr: "kend", mon: "333333333333"},
{id: 992, hun: "Zsezse", ltn: "Acanthis flammea", abr: "zsez", mon: "111111111111"},
{id: 993, hun: "Barna zsezse", ltn: "Acanthis cabaret", abr: "bnzs", mon: "111111111111"},
{id: 994, hun: "Zsezse faj", ltn: "Acanthis sp.", abr: "", mon: "111111111111"},
{id: 995, hun: "Szürke zsezse", ltn: "Acanthis hornemanni", abr: "", mon: "111111111111"},
{id: 996, hun: "Nagy keresztcsőrű", ltn: "Loxia pytyopsittacus", abr: "", mon: null},
{id: 997, hun: "Skót keresztcsőrű", ltn: "Loxia scotica", abr: "", mon: null},
{id: 998, hun: "Keresztcsőrű", ltn: "Loxia curvirostra", abr: "krcs", mon: "222222222222"},
{id: 999, hun: "Szalagos keresztcsőrű", ltn: "Loxia leucoptera", abr: "", mon: "111111111111"},
{id: 1000, hun: "Tengelic", ltn: "Carduelis carduelis", abr: "teng", mon: "333333333333"},
{id: 1001, hun: "Citromcsíz", ltn: "Carduelis citrinella", abr: "", mon: null},
{id: 1002, hun: "Korzikai citromcsíz", ltn: "Carduelis corsicana", abr: "", mon: null},
{id: 1003, hun: "Vöröshomlokú csicsörke", ltn: "Serinus pusillus", abr: "", mon: null},
{id: 1004, hun: "Csicsörke", ltn: "Serinus serinus", abr: "csic", mon: "223333333332"},
{id: 1005, hun: "Szíriai csicsörke", ltn: "Serinus syriacus", abr: "", mon: null},
{id: 1006, hun: "Kanári", ltn: "Serinus canaria", abr: "", mon: null},
{id: 1007, hun: "Csíz", ltn: "Spinus spinus", abr: "csiz", mon: "333322223333"},
{id: 1008, hun: "Sarkantyús sármány", ltn: "Calcarius lapponicus", abr: "sksm", mon: "111111111111"},
{id: 1009, hun: "Hósármány", ltn: "Plectrophenax nivalis", abr: "hosm", mon: "111111111111"},
{id: 1010, hun: "Sordély", ltn: "Emberiza calandra", abr: "sord", mon: "333333333333"},
{id: 1011, hun: "Citromsármány", ltn: "Emberiza citrinella", abr: "crsm,ctsm", mon: "333333333333"},
{id: 1012, hun: "Fenyősármány", ltn: "Emberiza leucocephalos", abr: "fnsm", mon: "111111111111"},
{id: 1013, hun: "Bajszos sármány", ltn: "Emberiza cia", abr: "bssm,bjsm", mon: "222222222222"},
{id: 1014, hun: "Kövi sármány", ltn: "Emberiza buchanani", abr: "", mon: null},
{id: 1015, hun: "Szürke sármány", ltn: "Emberiza cineracea", abr: "", mon: null},
{id: 1016, hun: "Kerti sármány", ltn: "Emberiza hortulana", abr: "ktsm", mon: "111111111111"},
{id: 1017, hun: "Rozsdás sármány", ltn: "Emberiza caesia", abr: "", mon: null},
{id: 1018, hun: "Sövénysármány", ltn: "Emberiza cirlus", abr: "svsm", mon: "111111111111"},
{id: 1019, hun: "Sivatagi sármány", ltn: "Emberiza striolata", abr: "", mon: null},
{id: 1020, hun: "Szaharai sármány", ltn: "Emberiza sahari", abr: "", mon: null},
{id: 1021, hun: "Barnafülű sármány", ltn: "Emberiza fucata", abr: "", mon: null},
{id: 1022, hun: "Törpesármány", ltn: "Emberiza pusilla", abr: "tpsm", mon: "111111111111"},
{id: 1023, hun: "Tajgasármány", ltn: "Emberiza chrysophrys", abr: "", mon: null},
{id: 1024, hun: "Erdei sármány", ltn: "Emberiza rustica", abr: "ersm", mon: "111111111111"},
{id: 1025, hun: "Aranyos sármány", ltn: "Emberiza aureola", abr: "", mon: null},
{id: 1026, hun: "Vörhenyes sármány", ltn: "Emberiza rutila", abr: "", mon: "000000000000"},
{id: 1027, hun: "Kucsmás sármány", ltn: "Emberiza melanocephala", abr: "kmsm", mon: "111111111111"},
{id: 1028, hun: "Vörösfejű sármány", ltn: "Emberiza bruniceps", abr: "", mon: null},
{id: 1029, hun: "Feketearcú sármány", ltn: "Emberiza spodocephala", abr: "", mon: null},
{id: 1030, hun: "Szürkevállú sármány", ltn: "Emberiza pallasi", abr: "", mon: null},
{id: 1031, hun: "Nádi sármány", ltn: "Emberiza schoeniclus", abr: "nasa,ndsm", mon: "333333333333"},
{id: 1032, hun: "Pacsirtasármány", ltn: "Chondestes grammacus", abr: "", mon: null},
{id: 1033, hun: "Vörhenyes verébsármány", ltn: "Passerella iliaca", abr: "", mon: null},
{id: 1034, hun: "Erdei verébsármány", ltn: "Spizelloides arborea", abr: "", mon: null},
{id: 1035, hun: "Füstös junkó", ltn: "Junco hyemalis", abr: "", mon: null},
{id: 1036, hun: "Koronás verébsármány", ltn: "Zonotrichia leucophrys", abr: "", mon: null},
{id: 1037, hun: "Fehértorkú verébsármány", ltn: "Zonotrichia albicollis", abr: "", mon: null},
{id: 1038, hun: "Mezei verébsármány", ltn: "Passerculus sandwichensis", abr: "", mon: null},
{id: 1039, hun: "Énekes verébsármány", ltn: "Melospiza melodia", abr: "", mon: null},
{id: 1040, hun: "Lincoln-verébsármány", ltn: "Melospiza lincolnii", abr: "", mon: null},
{id: 1041, hun: "Tarka avarsármány", ltn: "Pipilo erythrophthalmus", abr: "", mon: null},
{id: 1042, hun: "Sárgafejű csiröge", ltn: "Xanthocephalus xanthocephalus", abr: "", mon: null},
{id: 1043, hun: "Seregélysármány", ltn: "Dolichonyx oryzivorus", abr: "", mon: null},
{id: 1044, hun: "Narancstrupiál", ltn: "Icterus galbula", abr: "", mon: null},
{id: 1045, hun: "Pirosvállú csiröge", ltn: "Agelaius phoeniceus", abr: "", mon: null},
{id: 1046, hun: "Barnafejű gulyajáró", ltn: "Molothrus ater", abr: "", mon: null},
{id: 1047, hun: "Szerecsenmadár", ltn: "Quiscalus quiscula", abr: "", mon: null},
{id: 1048, hun: "Koronás harasztjáró", ltn: "Seiurus aurocapilla", abr: "", mon: null},
{id: 1049, hun: "Lápi harasztjáró", ltn: "Parkesia noveboracensis", abr: "", mon: null},
{id: 1050, hun: "Aranyszárnyú hernyófaló", ltn: "Vermivora chrysoptera", abr: "", mon: null},
{id: 1051, hun: "Kékszárnyú hernyófaló", ltn: "Vermivora cyanoptera", abr: "", mon: null},
{id: 1052, hun: "Csíkos kéregjáró", ltn: "Mniotilta varia", abr: "", mon: null},
{id: 1053, hun: "Citromlombjáró", ltn: "Protonotaria citrea", abr: "", mon: null},
{id: 1054, hun: "Szürkefejű hernyófaló", ltn: "Leiothlypis peregrina", abr: "", mon: null},
{id: 1055, hun: "Fürge lombjáró", ltn: "Oporornis agilis", abr: "", mon: null},
{id: 1056, hun: "Északi álarcosposzáta", ltn: "Geothlypis trichas", abr: "", mon: null},
{id: 1057, hun: "Csuklyás lombjáró", ltn: "Setophaga citrina", abr: "", mon: null},
{id: 1058, hun: "Legyezőfarkú lombposzáta", ltn: "Setophaga ruticilla", abr: "", mon: null},
{id: 1059, hun: "Tigrislombjáró", ltn: "Setophaga tigrina", abr: "", mon: null},
{id: 1060, hun: "Lazúrlombjáró", ltn: "Setophaga cerulea", abr: "", mon: null},
{id: 1061, hun: "Északi lombposzáta", ltn: "Setophaga americana", abr: "", mon: null},
{id: 1062, hun: "Magnólialombjáró", ltn: "Setophaga magnolia", abr: "", mon: null},
{id: 1063, hun: "Rozsdás lombjáró", ltn: "Setophaga castanea", abr: "", mon: null},
{id: 1064, hun: "Narancstorkú lombjáró", ltn: "Setophaga fusca", abr: "", mon: null},
{id: 1065, hun: "Sárga lombjáró", ltn: "Setophaga aestiva", abr: "", mon: null},
{id: 1066, hun: "Barkós lombjáró", ltn: "Setophaga pensylvanica", abr: "", mon: null},
{id: 1067, hun: "Kucsmás lombjáró", ltn: "Setophaga striata", abr: "", mon: null},
{id: 1068, hun: "Kékes lombjáró", ltn: "Setophaga caerulescens", abr: "", mon: null},
{id: 1069, hun: "Billegető lombjáró", ltn: "Setophaga palmarum", abr: "", mon: null},
{id: 1070, hun: "Koronás lombjáró", ltn: "Setophaga coronata", abr: "", mon: null},
{id: 1071, hun: "Sárgatorkú lombjáró", ltn: "Setophaga dominica", abr: "", mon: null},
{id: 1072, hun: "Préri lombjáró", ltn: "Setophaga discolor", abr: "", mon: null},
{id: 1073, hun: "Feketetorkú lombjáró", ltn: "Setophaga virens", abr: "", mon: null},
{id: 1074, hun: "Örvös lombjáró", ltn: "Cardellina canadensis", abr: "", mon: null},
{id: 1075, hun: "Sapkás lombjáró", ltn: "Cardellina pusilla", abr: "", mon: null},
{id: 1076, hun: "Piros tangara", ltn: "Piranga rubra", abr: "", mon: null},
{id: 1077, hun: "Skarláttangara", ltn: "Piranga olivacea", abr: "", mon: null},
{id: 1078, hun: "Vörösmellű magvágó", ltn: "Pheucticus ludovicianus", abr: "", mon: null},
{id: 1079, hun: "Préripinty", ltn: "Spiza americana", abr: "", mon: null},
{id: 1080, hun: "Kék magtörő", ltn: "Passerina caerulea", abr: "", mon: null},
{id: 1081, hun: "Indigópinty", ltn: "Passerina cyanea", abr: "", mon: null},
{id: 1082, hun: "Hibrid", ltn: "Hybrid", abr: "hibr", mon: "222222222222"},
{id: 1083, hun: "Szökevény", ltn: "Escapee", abr: "szok", mon: "333333333333"},
{id: 1084, hun: "Egyéb", ltn: "Other", abr: "", mon: null}
]